// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * <pre>
 * EncryptedClientIdentification message used to hold ClientIdentification
 * messages encrypted for privacy purposes.
 * </pre>
 *
 * Protobuf type {@code EncryptedClientIdentification}
 */
public final class EncryptedClientIdentification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:EncryptedClientIdentification)
    EncryptedClientIdentificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EncryptedClientIdentification.newBuilder() to construct.
  private EncryptedClientIdentification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EncryptedClientIdentification() {
    providerId_ = "";
    serviceCertificateSerialNumber_ = com.google.protobuf.ByteString.EMPTY;
    encryptedClientId_ = com.google.protobuf.ByteString.EMPTY;
    encryptedClientIdIv_ = com.google.protobuf.ByteString.EMPTY;
    encryptedPrivacyKey_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EncryptedClientIdentification();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_EncryptedClientIdentification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_EncryptedClientIdentification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification.class, de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification.Builder.class);
  }

  private int bitField0_;
  public static final int PROVIDER_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object providerId_ = "";
  /**
   * <pre>
   * Provider ID for which the ClientIdentifcation is encrypted (owner of
   * service certificate).
   * </pre>
   *
   * <code>optional string provider_id = 1;</code>
   * @return Whether the providerId field is set.
   */
  @java.lang.Override
  public boolean hasProviderId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Provider ID for which the ClientIdentifcation is encrypted (owner of
   * service certificate).
   * </pre>
   *
   * <code>optional string provider_id = 1;</code>
   * @return The providerId.
   */
  @java.lang.Override
  public java.lang.String getProviderId() {
    java.lang.Object ref = providerId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        providerId_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * Provider ID for which the ClientIdentifcation is encrypted (owner of
   * service certificate).
   * </pre>
   *
   * <code>optional string provider_id = 1;</code>
   * @return The bytes for providerId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getProviderIdBytes() {
    java.lang.Object ref = providerId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      providerId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SERVICE_CERTIFICATE_SERIAL_NUMBER_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString serviceCertificateSerialNumber_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Serial number for the service certificate for which ClientIdentification is
   * encrypted.
   * </pre>
   *
   * <code>optional bytes service_certificate_serial_number = 2;</code>
   * @return Whether the serviceCertificateSerialNumber field is set.
   */
  @java.lang.Override
  public boolean hasServiceCertificateSerialNumber() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Serial number for the service certificate for which ClientIdentification is
   * encrypted.
   * </pre>
   *
   * <code>optional bytes service_certificate_serial_number = 2;</code>
   * @return The serviceCertificateSerialNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getServiceCertificateSerialNumber() {
    return serviceCertificateSerialNumber_;
  }

  public static final int ENCRYPTED_CLIENT_ID_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString encryptedClientId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Serialized ClientIdentification message, encrypted with the privacy key
   * using AES-128-CBC with PKCS#5 padding.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id = 3;</code>
   * @return Whether the encryptedClientId field is set.
   */
  @java.lang.Override
  public boolean hasEncryptedClientId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Serialized ClientIdentification message, encrypted with the privacy key
   * using AES-128-CBC with PKCS#5 padding.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id = 3;</code>
   * @return The encryptedClientId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedClientId() {
    return encryptedClientId_;
  }

  public static final int ENCRYPTED_CLIENT_ID_IV_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString encryptedClientIdIv_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Initialization vector needed to decrypt encrypted_client_id.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id_iv = 4;</code>
   * @return Whether the encryptedClientIdIv field is set.
   */
  @java.lang.Override
  public boolean hasEncryptedClientIdIv() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Initialization vector needed to decrypt encrypted_client_id.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id_iv = 4;</code>
   * @return The encryptedClientIdIv.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedClientIdIv() {
    return encryptedClientIdIv_;
  }

  public static final int ENCRYPTED_PRIVACY_KEY_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString encryptedPrivacyKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
   * </pre>
   *
   * <code>optional bytes encrypted_privacy_key = 5;</code>
   * @return Whether the encryptedPrivacyKey field is set.
   */
  @java.lang.Override
  public boolean hasEncryptedPrivacyKey() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
   * </pre>
   *
   * <code>optional bytes encrypted_privacy_key = 5;</code>
   * @return The encryptedPrivacyKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getEncryptedPrivacyKey() {
    return encryptedPrivacyKey_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, providerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, serviceCertificateSerialNumber_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, encryptedClientId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, encryptedClientIdIv_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBytes(5, encryptedPrivacyKey_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, providerId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, serviceCertificateSerialNumber_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, encryptedClientId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, encryptedClientIdIv_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, encryptedPrivacyKey_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification)) {
      return super.equals(obj);
    }
    de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification other = (de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification) obj;

    if (hasProviderId() != other.hasProviderId()) return false;
    if (hasProviderId()) {
      if (!getProviderId()
          .equals(other.getProviderId())) return false;
    }
    if (hasServiceCertificateSerialNumber() != other.hasServiceCertificateSerialNumber()) return false;
    if (hasServiceCertificateSerialNumber()) {
      if (!getServiceCertificateSerialNumber()
          .equals(other.getServiceCertificateSerialNumber())) return false;
    }
    if (hasEncryptedClientId() != other.hasEncryptedClientId()) return false;
    if (hasEncryptedClientId()) {
      if (!getEncryptedClientId()
          .equals(other.getEncryptedClientId())) return false;
    }
    if (hasEncryptedClientIdIv() != other.hasEncryptedClientIdIv()) return false;
    if (hasEncryptedClientIdIv()) {
      if (!getEncryptedClientIdIv()
          .equals(other.getEncryptedClientIdIv())) return false;
    }
    if (hasEncryptedPrivacyKey() != other.hasEncryptedPrivacyKey()) return false;
    if (hasEncryptedPrivacyKey()) {
      if (!getEncryptedPrivacyKey()
          .equals(other.getEncryptedPrivacyKey())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasProviderId()) {
      hash = (37 * hash) + PROVIDER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getProviderId().hashCode();
    }
    if (hasServiceCertificateSerialNumber()) {
      hash = (37 * hash) + SERVICE_CERTIFICATE_SERIAL_NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getServiceCertificateSerialNumber().hashCode();
    }
    if (hasEncryptedClientId()) {
      hash = (37 * hash) + ENCRYPTED_CLIENT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedClientId().hashCode();
    }
    if (hasEncryptedClientIdIv()) {
      hash = (37 * hash) + ENCRYPTED_CLIENT_ID_IV_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedClientIdIv().hashCode();
    }
    if (hasEncryptedPrivacyKey()) {
      hash = (37 * hash) + ENCRYPTED_PRIVACY_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getEncryptedPrivacyKey().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * EncryptedClientIdentification message used to hold ClientIdentification
   * messages encrypted for privacy purposes.
   * </pre>
   *
   * Protobuf type {@code EncryptedClientIdentification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:EncryptedClientIdentification)
      de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_EncryptedClientIdentification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_EncryptedClientIdentification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification.class, de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification.Builder.class);
    }

    // Construct using de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      providerId_ = "";
      serviceCertificateSerialNumber_ = com.google.protobuf.ByteString.EMPTY;
      encryptedClientId_ = com.google.protobuf.ByteString.EMPTY;
      encryptedClientIdIv_ = com.google.protobuf.ByteString.EMPTY;
      encryptedPrivacyKey_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_EncryptedClientIdentification_descriptor;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification getDefaultInstanceForType() {
      return de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification.getDefaultInstance();
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification build() {
      de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification buildPartial() {
      de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification result = new de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.providerId_ = providerId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.serviceCertificateSerialNumber_ = serviceCertificateSerialNumber_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.encryptedClientId_ = encryptedClientId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.encryptedClientIdIv_ = encryptedClientIdIv_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.encryptedPrivacyKey_ = encryptedPrivacyKey_;
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification) {
        return mergeFrom((de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification other) {
      if (other == de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification.getDefaultInstance()) return this;
      if (other.hasProviderId()) {
        providerId_ = other.providerId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasServiceCertificateSerialNumber()) {
        setServiceCertificateSerialNumber(other.getServiceCertificateSerialNumber());
      }
      if (other.hasEncryptedClientId()) {
        setEncryptedClientId(other.getEncryptedClientId());
      }
      if (other.hasEncryptedClientIdIv()) {
        setEncryptedClientIdIv(other.getEncryptedClientIdIv());
      }
      if (other.hasEncryptedPrivacyKey()) {
        setEncryptedPrivacyKey(other.getEncryptedPrivacyKey());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              providerId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              serviceCertificateSerialNumber_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              encryptedClientId_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              encryptedClientIdIv_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              encryptedPrivacyKey_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object providerId_ = "";
    /**
     * <pre>
     * Provider ID for which the ClientIdentifcation is encrypted (owner of
     * service certificate).
     * </pre>
     *
     * <code>optional string provider_id = 1;</code>
     * @return Whether the providerId field is set.
     */
    public boolean hasProviderId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Provider ID for which the ClientIdentifcation is encrypted (owner of
     * service certificate).
     * </pre>
     *
     * <code>optional string provider_id = 1;</code>
     * @return The providerId.
     */
    public java.lang.String getProviderId() {
      java.lang.Object ref = providerId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          providerId_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Provider ID for which the ClientIdentifcation is encrypted (owner of
     * service certificate).
     * </pre>
     *
     * <code>optional string provider_id = 1;</code>
     * @return The bytes for providerId.
     */
    public com.google.protobuf.ByteString
        getProviderIdBytes() {
      java.lang.Object ref = providerId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        providerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Provider ID for which the ClientIdentifcation is encrypted (owner of
     * service certificate).
     * </pre>
     *
     * <code>optional string provider_id = 1;</code>
     * @param value The providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      providerId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Provider ID for which the ClientIdentifcation is encrypted (owner of
     * service certificate).
     * </pre>
     *
     * <code>optional string provider_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderId() {
      providerId_ = getDefaultInstance().getProviderId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Provider ID for which the ClientIdentifcation is encrypted (owner of
     * service certificate).
     * </pre>
     *
     * <code>optional string provider_id = 1;</code>
     * @param value The bytes for providerId to set.
     * @return This builder for chaining.
     */
    public Builder setProviderIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      providerId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString serviceCertificateSerialNumber_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Serial number for the service certificate for which ClientIdentification is
     * encrypted.
     * </pre>
     *
     * <code>optional bytes service_certificate_serial_number = 2;</code>
     * @return Whether the serviceCertificateSerialNumber field is set.
     */
    @java.lang.Override
    public boolean hasServiceCertificateSerialNumber() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Serial number for the service certificate for which ClientIdentification is
     * encrypted.
     * </pre>
     *
     * <code>optional bytes service_certificate_serial_number = 2;</code>
     * @return The serviceCertificateSerialNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getServiceCertificateSerialNumber() {
      return serviceCertificateSerialNumber_;
    }
    /**
     * <pre>
     * Serial number for the service certificate for which ClientIdentification is
     * encrypted.
     * </pre>
     *
     * <code>optional bytes service_certificate_serial_number = 2;</code>
     * @param value The serviceCertificateSerialNumber to set.
     * @return This builder for chaining.
     */
    public Builder setServiceCertificateSerialNumber(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      serviceCertificateSerialNumber_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serial number for the service certificate for which ClientIdentification is
     * encrypted.
     * </pre>
     *
     * <code>optional bytes service_certificate_serial_number = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceCertificateSerialNumber() {
      bitField0_ = (bitField0_ & ~0x00000002);
      serviceCertificateSerialNumber_ = getDefaultInstance().getServiceCertificateSerialNumber();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encryptedClientId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Serialized ClientIdentification message, encrypted with the privacy key
     * using AES-128-CBC with PKCS#5 padding.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id = 3;</code>
     * @return Whether the encryptedClientId field is set.
     */
    @java.lang.Override
    public boolean hasEncryptedClientId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Serialized ClientIdentification message, encrypted with the privacy key
     * using AES-128-CBC with PKCS#5 padding.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id = 3;</code>
     * @return The encryptedClientId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedClientId() {
      return encryptedClientId_;
    }
    /**
     * <pre>
     * Serialized ClientIdentification message, encrypted with the privacy key
     * using AES-128-CBC with PKCS#5 padding.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id = 3;</code>
     * @param value The encryptedClientId to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedClientId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      encryptedClientId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialized ClientIdentification message, encrypted with the privacy key
     * using AES-128-CBC with PKCS#5 padding.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedClientId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      encryptedClientId_ = getDefaultInstance().getEncryptedClientId();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encryptedClientIdIv_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Initialization vector needed to decrypt encrypted_client_id.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id_iv = 4;</code>
     * @return Whether the encryptedClientIdIv field is set.
     */
    @java.lang.Override
    public boolean hasEncryptedClientIdIv() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Initialization vector needed to decrypt encrypted_client_id.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id_iv = 4;</code>
     * @return The encryptedClientIdIv.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedClientIdIv() {
      return encryptedClientIdIv_;
    }
    /**
     * <pre>
     * Initialization vector needed to decrypt encrypted_client_id.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id_iv = 4;</code>
     * @param value The encryptedClientIdIv to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedClientIdIv(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      encryptedClientIdIv_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Initialization vector needed to decrypt encrypted_client_id.
     * </pre>
     *
     * <code>optional bytes encrypted_client_id_iv = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedClientIdIv() {
      bitField0_ = (bitField0_ & ~0x00000008);
      encryptedClientIdIv_ = getDefaultInstance().getEncryptedClientIdIv();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString encryptedPrivacyKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
     * </pre>
     *
     * <code>optional bytes encrypted_privacy_key = 5;</code>
     * @return Whether the encryptedPrivacyKey field is set.
     */
    @java.lang.Override
    public boolean hasEncryptedPrivacyKey() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
     * </pre>
     *
     * <code>optional bytes encrypted_privacy_key = 5;</code>
     * @return The encryptedPrivacyKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEncryptedPrivacyKey() {
      return encryptedPrivacyKey_;
    }
    /**
     * <pre>
     * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
     * </pre>
     *
     * <code>optional bytes encrypted_privacy_key = 5;</code>
     * @param value The encryptedPrivacyKey to set.
     * @return This builder for chaining.
     */
    public Builder setEncryptedPrivacyKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      encryptedPrivacyKey_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
     * </pre>
     *
     * <code>optional bytes encrypted_privacy_key = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearEncryptedPrivacyKey() {
      bitField0_ = (bitField0_ & ~0x00000010);
      encryptedPrivacyKey_ = getDefaultInstance().getEncryptedPrivacyKey();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:EncryptedClientIdentification)
  }

  // @@protoc_insertion_point(class_scope:EncryptedClientIdentification)
  private static final de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification();
  }

  public static de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<EncryptedClientIdentification>
      PARSER = new com.google.protobuf.AbstractParser<EncryptedClientIdentification>() {
    @java.lang.Override
    public EncryptedClientIdentification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<EncryptedClientIdentification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EncryptedClientIdentification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.EncryptedClientIdentification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

