// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface EncryptedClientIdentificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EncryptedClientIdentification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Provider ID for which the ClientIdentifcation is encrypted (owner of
   * service certificate).
   * </pre>
   *
   * <code>optional string provider_id = 1;</code>
   * @return Whether the providerId field is set.
   */
  boolean hasProviderId();
  /**
   * <pre>
   * Provider ID for which the ClientIdentifcation is encrypted (owner of
   * service certificate).
   * </pre>
   *
   * <code>optional string provider_id = 1;</code>
   * @return The providerId.
   */
  java.lang.String getProviderId();
  /**
   * <pre>
   * Provider ID for which the ClientIdentifcation is encrypted (owner of
   * service certificate).
   * </pre>
   *
   * <code>optional string provider_id = 1;</code>
   * @return The bytes for providerId.
   */
  com.google.protobuf.ByteString
      getProviderIdBytes();

  /**
   * <pre>
   * Serial number for the service certificate for which ClientIdentification is
   * encrypted.
   * </pre>
   *
   * <code>optional bytes service_certificate_serial_number = 2;</code>
   * @return Whether the serviceCertificateSerialNumber field is set.
   */
  boolean hasServiceCertificateSerialNumber();
  /**
   * <pre>
   * Serial number for the service certificate for which ClientIdentification is
   * encrypted.
   * </pre>
   *
   * <code>optional bytes service_certificate_serial_number = 2;</code>
   * @return The serviceCertificateSerialNumber.
   */
  com.google.protobuf.ByteString getServiceCertificateSerialNumber();

  /**
   * <pre>
   * Serialized ClientIdentification message, encrypted with the privacy key
   * using AES-128-CBC with PKCS#5 padding.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id = 3;</code>
   * @return Whether the encryptedClientId field is set.
   */
  boolean hasEncryptedClientId();
  /**
   * <pre>
   * Serialized ClientIdentification message, encrypted with the privacy key
   * using AES-128-CBC with PKCS#5 padding.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id = 3;</code>
   * @return The encryptedClientId.
   */
  com.google.protobuf.ByteString getEncryptedClientId();

  /**
   * <pre>
   * Initialization vector needed to decrypt encrypted_client_id.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id_iv = 4;</code>
   * @return Whether the encryptedClientIdIv field is set.
   */
  boolean hasEncryptedClientIdIv();
  /**
   * <pre>
   * Initialization vector needed to decrypt encrypted_client_id.
   * </pre>
   *
   * <code>optional bytes encrypted_client_id_iv = 4;</code>
   * @return The encryptedClientIdIv.
   */
  com.google.protobuf.ByteString getEncryptedClientIdIv();

  /**
   * <pre>
   * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
   * </pre>
   *
   * <code>optional bytes encrypted_privacy_key = 5;</code>
   * @return Whether the encryptedPrivacyKey field is set.
   */
  boolean hasEncryptedPrivacyKey();
  /**
   * <pre>
   * AES-128 privacy key, encrypted with the service public key using RSA-OAEP.
   * </pre>
   *
   * <code>optional bytes encrypted_privacy_key = 5;</code>
   * @return The encryptedPrivacyKey.
   */
  com.google.protobuf.ByteString getEncryptedPrivacyKey();
}
