// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface FileHashesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FileHashes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes signer = 1;</code>
   * @return Whether the signer field is set.
   */
  boolean hasSigner();
  /**
   * <code>optional bytes signer = 1;</code>
   * @return The signer.
   */
  com.google.protobuf.ByteString getSigner();

  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  java.util.List<de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature> 
      getSignaturesList();
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature getSignatures(int index);
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  int getSignaturesCount();
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder> 
      getSignaturesOrBuilderList();
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder getSignaturesOrBuilder(
      int index);
}
