// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * <pre>
 * File Hashes for Verified Media Path (VMP) support.
 * </pre>
 *
 * Protobuf type {@code FileHashes}
 */
public final class FileHashes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FileHashes)
    FileHashesOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileHashes.newBuilder() to construct.
  private FileHashes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileHashes() {
    signer_ = com.google.protobuf.ByteString.EMPTY;
    signatures_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FileHashes();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.klassenserver7b.widevine4j.protobuf.FileHashes.class, de.klassenserver7b.widevine4j.protobuf.FileHashes.Builder.class);
  }

  public interface SignatureOrBuilder extends
      // @@protoc_insertion_point(interface_extends:FileHashes.Signature)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string filename = 1;</code>
     * @return Whether the filename field is set.
     */
    boolean hasFilename();
    /**
     * <code>optional string filename = 1;</code>
     * @return The filename.
     */
    java.lang.String getFilename();
    /**
     * <code>optional string filename = 1;</code>
     * @return The bytes for filename.
     */
    com.google.protobuf.ByteString
        getFilenameBytes();

    /**
     * <pre>
     *0 - release, 1 - testing
     * </pre>
     *
     * <code>optional bool test_signing = 2;</code>
     * @return Whether the testSigning field is set.
     */
    boolean hasTestSigning();
    /**
     * <pre>
     *0 - release, 1 - testing
     * </pre>
     *
     * <code>optional bool test_signing = 2;</code>
     * @return The testSigning.
     */
    boolean getTestSigning();

    /**
     * <code>optional bytes SHA512Hash = 3;</code>
     * @return Whether the sHA512Hash field is set.
     */
    boolean hasSHA512Hash();
    /**
     * <code>optional bytes SHA512Hash = 3;</code>
     * @return The sHA512Hash.
     */
    com.google.protobuf.ByteString getSHA512Hash();

    /**
     * <pre>
     *0 for dlls, 1 for exe, this is field 3 in file
     * </pre>
     *
     * <code>optional bool main_exe = 4;</code>
     * @return Whether the mainExe field is set.
     */
    boolean hasMainExe();
    /**
     * <pre>
     *0 for dlls, 1 for exe, this is field 3 in file
     * </pre>
     *
     * <code>optional bool main_exe = 4;</code>
     * @return The mainExe.
     */
    boolean getMainExe();

    /**
     * <code>optional bytes signature = 5;</code>
     * @return Whether the signature field is set.
     */
    boolean hasSignature();
    /**
     * <code>optional bytes signature = 5;</code>
     * @return The signature.
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code FileHashes.Signature}
   */
  public static final class Signature extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:FileHashes.Signature)
      SignatureOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Signature.newBuilder() to construct.
    private Signature(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Signature() {
      filename_ = "";
      sHA512Hash_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Signature();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_Signature_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_Signature_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.class, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder.class);
    }

    private int bitField0_;
    public static final int FILENAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object filename_ = "";
    /**
     * <code>optional string filename = 1;</code>
     * @return Whether the filename field is set.
     */
    @java.lang.Override
    public boolean hasFilename() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string filename = 1;</code>
     * @return The filename.
     */
    @java.lang.Override
    public java.lang.String getFilename() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          filename_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string filename = 1;</code>
     * @return The bytes for filename.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      java.lang.Object ref = filename_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        filename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEST_SIGNING_FIELD_NUMBER = 2;
    private boolean testSigning_ = false;
    /**
     * <pre>
     *0 - release, 1 - testing
     * </pre>
     *
     * <code>optional bool test_signing = 2;</code>
     * @return Whether the testSigning field is set.
     */
    @java.lang.Override
    public boolean hasTestSigning() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     *0 - release, 1 - testing
     * </pre>
     *
     * <code>optional bool test_signing = 2;</code>
     * @return The testSigning.
     */
    @java.lang.Override
    public boolean getTestSigning() {
      return testSigning_;
    }

    public static final int SHA512HASH_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString sHA512Hash_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes SHA512Hash = 3;</code>
     * @return Whether the sHA512Hash field is set.
     */
    @java.lang.Override
    public boolean hasSHA512Hash() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes SHA512Hash = 3;</code>
     * @return The sHA512Hash.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSHA512Hash() {
      return sHA512Hash_;
    }

    public static final int MAIN_EXE_FIELD_NUMBER = 4;
    private boolean mainExe_ = false;
    /**
     * <pre>
     *0 for dlls, 1 for exe, this is field 3 in file
     * </pre>
     *
     * <code>optional bool main_exe = 4;</code>
     * @return Whether the mainExe field is set.
     */
    @java.lang.Override
    public boolean hasMainExe() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     *0 for dlls, 1 for exe, this is field 3 in file
     * </pre>
     *
     * <code>optional bool main_exe = 4;</code>
     * @return The mainExe.
     */
    @java.lang.Override
    public boolean getMainExe() {
      return mainExe_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes signature = 5;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional bytes signature = 5;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, filename_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeBool(2, testSigning_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeBytes(3, sHA512Hash_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, mainExe_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBytes(5, signature_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, filename_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, testSigning_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, sHA512Hash_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, mainExe_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, signature_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature)) {
        return super.equals(obj);
      }
      de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature other = (de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature) obj;

      if (hasFilename() != other.hasFilename()) return false;
      if (hasFilename()) {
        if (!getFilename()
            .equals(other.getFilename())) return false;
      }
      if (hasTestSigning() != other.hasTestSigning()) return false;
      if (hasTestSigning()) {
        if (getTestSigning()
            != other.getTestSigning()) return false;
      }
      if (hasSHA512Hash() != other.hasSHA512Hash()) return false;
      if (hasSHA512Hash()) {
        if (!getSHA512Hash()
            .equals(other.getSHA512Hash())) return false;
      }
      if (hasMainExe() != other.hasMainExe()) return false;
      if (hasMainExe()) {
        if (getMainExe()
            != other.getMainExe()) return false;
      }
      if (hasSignature() != other.hasSignature()) return false;
      if (hasSignature()) {
        if (!getSignature()
            .equals(other.getSignature())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFilename()) {
        hash = (37 * hash) + FILENAME_FIELD_NUMBER;
        hash = (53 * hash) + getFilename().hashCode();
      }
      if (hasTestSigning()) {
        hash = (37 * hash) + TEST_SIGNING_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getTestSigning());
      }
      if (hasSHA512Hash()) {
        hash = (37 * hash) + SHA512HASH_FIELD_NUMBER;
        hash = (53 * hash) + getSHA512Hash().hashCode();
      }
      if (hasMainExe()) {
        hash = (37 * hash) + MAIN_EXE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getMainExe());
      }
      if (hasSignature()) {
        hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
        hash = (53 * hash) + getSignature().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code FileHashes.Signature}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:FileHashes.Signature)
        de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_Signature_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_Signature_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.class, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder.class);
      }

      // Construct using de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        filename_ = "";
        testSigning_ = false;
        sHA512Hash_ = com.google.protobuf.ByteString.EMPTY;
        mainExe_ = false;
        signature_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_Signature_descriptor;
      }

      @java.lang.Override
      public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature getDefaultInstanceForType() {
        return de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.getDefaultInstance();
      }

      @java.lang.Override
      public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature build() {
        de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature buildPartial() {
        de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature result = new de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.filename_ = filename_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.testSigning_ = testSigning_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.sHA512Hash_ = sHA512Hash_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.mainExe_ = mainExe_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.signature_ = signature_;
          to_bitField0_ |= 0x00000010;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature) {
          return mergeFrom((de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature other) {
        if (other == de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.getDefaultInstance()) return this;
        if (other.hasFilename()) {
          filename_ = other.filename_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasTestSigning()) {
          setTestSigning(other.getTestSigning());
        }
        if (other.hasSHA512Hash()) {
          setSHA512Hash(other.getSHA512Hash());
        }
        if (other.hasMainExe()) {
          setMainExe(other.getMainExe());
        }
        if (other.hasSignature()) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                filename_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                testSigning_ = input.readBool();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                sHA512Hash_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 32: {
                mainExe_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                signature_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object filename_ = "";
      /**
       * <code>optional string filename = 1;</code>
       * @return Whether the filename field is set.
       */
      public boolean hasFilename() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return The filename.
       */
      public java.lang.String getFilename() {
        java.lang.Object ref = filename_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            filename_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return The bytes for filename.
       */
      public com.google.protobuf.ByteString
          getFilenameBytes() {
        java.lang.Object ref = filename_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          filename_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string filename = 1;</code>
       * @param value The filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilename(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        filename_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearFilename() {
        filename_ = getDefaultInstance().getFilename();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string filename = 1;</code>
       * @param value The bytes for filename to set.
       * @return This builder for chaining.
       */
      public Builder setFilenameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        filename_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private boolean testSigning_ ;
      /**
       * <pre>
       *0 - release, 1 - testing
       * </pre>
       *
       * <code>optional bool test_signing = 2;</code>
       * @return Whether the testSigning field is set.
       */
      @java.lang.Override
      public boolean hasTestSigning() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       *0 - release, 1 - testing
       * </pre>
       *
       * <code>optional bool test_signing = 2;</code>
       * @return The testSigning.
       */
      @java.lang.Override
      public boolean getTestSigning() {
        return testSigning_;
      }
      /**
       * <pre>
       *0 - release, 1 - testing
       * </pre>
       *
       * <code>optional bool test_signing = 2;</code>
       * @param value The testSigning to set.
       * @return This builder for chaining.
       */
      public Builder setTestSigning(boolean value) {

        testSigning_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0 - release, 1 - testing
       * </pre>
       *
       * <code>optional bool test_signing = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTestSigning() {
        bitField0_ = (bitField0_ & ~0x00000002);
        testSigning_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString sHA512Hash_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes SHA512Hash = 3;</code>
       * @return Whether the sHA512Hash field is set.
       */
      @java.lang.Override
      public boolean hasSHA512Hash() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional bytes SHA512Hash = 3;</code>
       * @return The sHA512Hash.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSHA512Hash() {
        return sHA512Hash_;
      }
      /**
       * <code>optional bytes SHA512Hash = 3;</code>
       * @param value The sHA512Hash to set.
       * @return This builder for chaining.
       */
      public Builder setSHA512Hash(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        sHA512Hash_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes SHA512Hash = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSHA512Hash() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sHA512Hash_ = getDefaultInstance().getSHA512Hash();
        onChanged();
        return this;
      }

      private boolean mainExe_ ;
      /**
       * <pre>
       *0 for dlls, 1 for exe, this is field 3 in file
       * </pre>
       *
       * <code>optional bool main_exe = 4;</code>
       * @return Whether the mainExe field is set.
       */
      @java.lang.Override
      public boolean hasMainExe() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       *0 for dlls, 1 for exe, this is field 3 in file
       * </pre>
       *
       * <code>optional bool main_exe = 4;</code>
       * @return The mainExe.
       */
      @java.lang.Override
      public boolean getMainExe() {
        return mainExe_;
      }
      /**
       * <pre>
       *0 for dlls, 1 for exe, this is field 3 in file
       * </pre>
       *
       * <code>optional bool main_exe = 4;</code>
       * @param value The mainExe to set.
       * @return This builder for chaining.
       */
      public Builder setMainExe(boolean value) {

        mainExe_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *0 for dlls, 1 for exe, this is field 3 in file
       * </pre>
       *
       * <code>optional bool main_exe = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMainExe() {
        bitField0_ = (bitField0_ & ~0x00000008);
        mainExe_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes signature = 5;</code>
       * @return Whether the signature field is set.
       */
      @java.lang.Override
      public boolean hasSignature() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional bytes signature = 5;</code>
       * @return The signature.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>optional bytes signature = 5;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        signature_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes signature = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        bitField0_ = (bitField0_ & ~0x00000010);
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:FileHashes.Signature)
    }

    // @@protoc_insertion_point(class_scope:FileHashes.Signature)
    private static final de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature();
    }

    public static de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Signature>
        PARSER = new com.google.protobuf.AbstractParser<Signature>() {
      @java.lang.Override
      public Signature parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Signature> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Signature> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int SIGNER_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString signer_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes signer = 1;</code>
   * @return Whether the signer field is set.
   */
  @java.lang.Override
  public boolean hasSigner() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes signer = 1;</code>
   * @return The signer.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSigner() {
    return signer_;
  }

  public static final int SIGNATURES_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature> signatures_;
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  @java.lang.Override
  public java.util.List<de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature> getSignaturesList() {
    return signatures_;
  }
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder> 
      getSignaturesOrBuilderList() {
    return signatures_;
  }
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  @java.lang.Override
  public int getSignaturesCount() {
    return signatures_.size();
  }
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature getSignatures(int index) {
    return signatures_.get(index);
  }
  /**
   * <code>repeated .FileHashes.Signature signatures = 2;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder getSignaturesOrBuilder(
      int index) {
    return signatures_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(1, signer_);
    }
    for (int i = 0; i < signatures_.size(); i++) {
      output.writeMessage(2, signatures_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, signer_);
    }
    for (int i = 0; i < signatures_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, signatures_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.FileHashes)) {
      return super.equals(obj);
    }
    de.klassenserver7b.widevine4j.protobuf.FileHashes other = (de.klassenserver7b.widevine4j.protobuf.FileHashes) obj;

    if (hasSigner() != other.hasSigner()) return false;
    if (hasSigner()) {
      if (!getSigner()
          .equals(other.getSigner())) return false;
    }
    if (!getSignaturesList()
        .equals(other.getSignaturesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSigner()) {
      hash = (37 * hash) + SIGNER_FIELD_NUMBER;
      hash = (53 * hash) + getSigner().hashCode();
    }
    if (getSignaturesCount() > 0) {
      hash = (37 * hash) + SIGNATURES_FIELD_NUMBER;
      hash = (53 * hash) + getSignaturesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.FileHashes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.FileHashes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * File Hashes for Verified Media Path (VMP) support.
   * </pre>
   *
   * Protobuf type {@code FileHashes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FileHashes)
      de.klassenserver7b.widevine4j.protobuf.FileHashesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.FileHashes.class, de.klassenserver7b.widevine4j.protobuf.FileHashes.Builder.class);
    }

    // Construct using de.klassenserver7b.widevine4j.protobuf.FileHashes.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      signer_ = com.google.protobuf.ByteString.EMPTY;
      if (signaturesBuilder_ == null) {
        signatures_ = java.util.Collections.emptyList();
      } else {
        signatures_ = null;
        signaturesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_FileHashes_descriptor;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.FileHashes getDefaultInstanceForType() {
      return de.klassenserver7b.widevine4j.protobuf.FileHashes.getDefaultInstance();
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.FileHashes build() {
      de.klassenserver7b.widevine4j.protobuf.FileHashes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.FileHashes buildPartial() {
      de.klassenserver7b.widevine4j.protobuf.FileHashes result = new de.klassenserver7b.widevine4j.protobuf.FileHashes(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(de.klassenserver7b.widevine4j.protobuf.FileHashes result) {
      if (signaturesBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          signatures_ = java.util.Collections.unmodifiableList(signatures_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.signatures_ = signatures_;
      } else {
        result.signatures_ = signaturesBuilder_.build();
      }
    }

    private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.FileHashes result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.signer_ = signer_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.klassenserver7b.widevine4j.protobuf.FileHashes) {
        return mergeFrom((de.klassenserver7b.widevine4j.protobuf.FileHashes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.FileHashes other) {
      if (other == de.klassenserver7b.widevine4j.protobuf.FileHashes.getDefaultInstance()) return this;
      if (other.hasSigner()) {
        setSigner(other.getSigner());
      }
      if (signaturesBuilder_ == null) {
        if (!other.signatures_.isEmpty()) {
          if (signatures_.isEmpty()) {
            signatures_ = other.signatures_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureSignaturesIsMutable();
            signatures_.addAll(other.signatures_);
          }
          onChanged();
        }
      } else {
        if (!other.signatures_.isEmpty()) {
          if (signaturesBuilder_.isEmpty()) {
            signaturesBuilder_.dispose();
            signaturesBuilder_ = null;
            signatures_ = other.signatures_;
            bitField0_ = (bitField0_ & ~0x00000002);
            signaturesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSignaturesFieldBuilder() : null;
          } else {
            signaturesBuilder_.addAllMessages(other.signatures_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              signer_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature m =
                  input.readMessage(
                      de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.PARSER,
                      extensionRegistry);
              if (signaturesBuilder_ == null) {
                ensureSignaturesIsMutable();
                signatures_.add(m);
              } else {
                signaturesBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString signer_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes signer = 1;</code>
     * @return Whether the signer field is set.
     */
    @java.lang.Override
    public boolean hasSigner() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes signer = 1;</code>
     * @return The signer.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSigner() {
      return signer_;
    }
    /**
     * <code>optional bytes signer = 1;</code>
     * @param value The signer to set.
     * @return This builder for chaining.
     */
    public Builder setSigner(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      signer_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes signer = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSigner() {
      bitField0_ = (bitField0_ & ~0x00000001);
      signer_ = getDefaultInstance().getSigner();
      onChanged();
      return this;
    }

    private java.util.List<de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature> signatures_ =
      java.util.Collections.emptyList();
    private void ensureSignaturesIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        signatures_ = new java.util.ArrayList<de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature>(signatures_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder, de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder> signaturesBuilder_;

    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public java.util.List<de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature> getSignaturesList() {
      if (signaturesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(signatures_);
      } else {
        return signaturesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public int getSignaturesCount() {
      if (signaturesBuilder_ == null) {
        return signatures_.size();
      } else {
        return signaturesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature getSignatures(int index) {
      if (signaturesBuilder_ == null) {
        return signatures_.get(index);
      } else {
        return signaturesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder setSignatures(
        int index, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature value) {
      if (signaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignaturesIsMutable();
        signatures_.set(index, value);
        onChanged();
      } else {
        signaturesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder setSignatures(
        int index, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder builderForValue) {
      if (signaturesBuilder_ == null) {
        ensureSignaturesIsMutable();
        signatures_.set(index, builderForValue.build());
        onChanged();
      } else {
        signaturesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder addSignatures(de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature value) {
      if (signaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignaturesIsMutable();
        signatures_.add(value);
        onChanged();
      } else {
        signaturesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder addSignatures(
        int index, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature value) {
      if (signaturesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSignaturesIsMutable();
        signatures_.add(index, value);
        onChanged();
      } else {
        signaturesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder addSignatures(
        de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder builderForValue) {
      if (signaturesBuilder_ == null) {
        ensureSignaturesIsMutable();
        signatures_.add(builderForValue.build());
        onChanged();
      } else {
        signaturesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder addSignatures(
        int index, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder builderForValue) {
      if (signaturesBuilder_ == null) {
        ensureSignaturesIsMutable();
        signatures_.add(index, builderForValue.build());
        onChanged();
      } else {
        signaturesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder addAllSignatures(
        java.lang.Iterable<? extends de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature> values) {
      if (signaturesBuilder_ == null) {
        ensureSignaturesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, signatures_);
        onChanged();
      } else {
        signaturesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder clearSignatures() {
      if (signaturesBuilder_ == null) {
        signatures_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        signaturesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public Builder removeSignatures(int index) {
      if (signaturesBuilder_ == null) {
        ensureSignaturesIsMutable();
        signatures_.remove(index);
        onChanged();
      } else {
        signaturesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder getSignaturesBuilder(
        int index) {
      return getSignaturesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder getSignaturesOrBuilder(
        int index) {
      if (signaturesBuilder_ == null) {
        return signatures_.get(index);  } else {
        return signaturesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder> 
         getSignaturesOrBuilderList() {
      if (signaturesBuilder_ != null) {
        return signaturesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(signatures_);
      }
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder addSignaturesBuilder() {
      return getSignaturesFieldBuilder().addBuilder(
          de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.getDefaultInstance());
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder addSignaturesBuilder(
        int index) {
      return getSignaturesFieldBuilder().addBuilder(
          index, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.getDefaultInstance());
    }
    /**
     * <code>repeated .FileHashes.Signature signatures = 2;</code>
     */
    public java.util.List<de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder> 
         getSignaturesBuilderList() {
      return getSignaturesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder, de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder> 
        getSignaturesFieldBuilder() {
      if (signaturesBuilder_ == null) {
        signaturesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature, de.klassenserver7b.widevine4j.protobuf.FileHashes.Signature.Builder, de.klassenserver7b.widevine4j.protobuf.FileHashes.SignatureOrBuilder>(
                signatures_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        signatures_ = null;
      }
      return signaturesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:FileHashes)
  }

  // @@protoc_insertion_point(class_scope:FileHashes)
  private static final de.klassenserver7b.widevine4j.protobuf.FileHashes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.FileHashes();
  }

  public static de.klassenserver7b.widevine4j.protobuf.FileHashes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<FileHashes>
      PARSER = new com.google.protobuf.AbstractParser<FileHashes>() {
    @java.lang.Override
    public FileHashes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<FileHashes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileHashes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.FileHashes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

