// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * Protobuf enum {@code HashAlgorithmProto}
 */
public enum HashAlgorithmProto
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <pre>
   * Unspecified hash algorithm: SHA_256 shall be used for ECC based algorithms
   * and SHA_1 shall be used otherwise.
   * </pre>
   *
   * <code>HASH_ALGORITHM_UNSPECIFIED = 0;</code>
   */
  HASH_ALGORITHM_UNSPECIFIED(0),
  /**
   * <code>HASH_ALGORITHM_SHA_1 = 1;</code>
   */
  HASH_ALGORITHM_SHA_1(1),
  /**
   * <code>HASH_ALGORITHM_SHA_256 = 2;</code>
   */
  HASH_ALGORITHM_SHA_256(2),
  /**
   * <code>HASH_ALGORITHM_SHA_384 = 3;</code>
   */
  HASH_ALGORITHM_SHA_384(3),
  ;

  /**
   * <pre>
   * Unspecified hash algorithm: SHA_256 shall be used for ECC based algorithms
   * and SHA_1 shall be used otherwise.
   * </pre>
   *
   * <code>HASH_ALGORITHM_UNSPECIFIED = 0;</code>
   */
  public static final int HASH_ALGORITHM_UNSPECIFIED_VALUE = 0;
  /**
   * <code>HASH_ALGORITHM_SHA_1 = 1;</code>
   */
  public static final int HASH_ALGORITHM_SHA_1_VALUE = 1;
  /**
   * <code>HASH_ALGORITHM_SHA_256 = 2;</code>
   */
  public static final int HASH_ALGORITHM_SHA_256_VALUE = 2;
  /**
   * <code>HASH_ALGORITHM_SHA_384 = 3;</code>
   */
  public static final int HASH_ALGORITHM_SHA_384_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HashAlgorithmProto valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static HashAlgorithmProto forNumber(int value) {
    switch (value) {
      case 0: return HASH_ALGORITHM_UNSPECIFIED;
      case 1: return HASH_ALGORITHM_SHA_1;
      case 2: return HASH_ALGORITHM_SHA_256;
      case 3: return HASH_ALGORITHM_SHA_384;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HashAlgorithmProto>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HashAlgorithmProto> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HashAlgorithmProto>() {
          public HashAlgorithmProto findValueByNumber(int number) {
            return HashAlgorithmProto.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.getDescriptor().getEnumTypes().get(3);
  }

  private static final HashAlgorithmProto[] VALUES = values();

  public static HashAlgorithmProto valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private HashAlgorithmProto(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:HashAlgorithmProto)
}

