// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface LicenseIdentificationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:LicenseIdentification)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional bytes request_id = 1;</code>
   * @return Whether the requestId field is set.
   */
  boolean hasRequestId();
  /**
   * <code>optional bytes request_id = 1;</code>
   * @return The requestId.
   */
  com.google.protobuf.ByteString getRequestId();

  /**
   * <code>optional bytes session_id = 2;</code>
   * @return Whether the sessionId field is set.
   */
  boolean hasSessionId();
  /**
   * <code>optional bytes session_id = 2;</code>
   * @return The sessionId.
   */
  com.google.protobuf.ByteString getSessionId();

  /**
   * <code>optional bytes purchase_id = 3;</code>
   * @return Whether the purchaseId field is set.
   */
  boolean hasPurchaseId();
  /**
   * <code>optional bytes purchase_id = 3;</code>
   * @return The purchaseId.
   */
  com.google.protobuf.ByteString getPurchaseId();

  /**
   * <code>optional .LicenseType type = 4;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional .LicenseType type = 4;</code>
   * @return The type.
   */
  de.klassenserver7b.widevine4j.protobuf.LicenseType getType();

  /**
   * <code>optional int32 version = 5;</code>
   * @return Whether the version field is set.
   */
  boolean hasVersion();
  /**
   * <code>optional int32 version = 5;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <code>optional bytes provider_session_token = 6;</code>
   * @return Whether the providerSessionToken field is set.
   */
  boolean hasProviderSessionToken();
  /**
   * <code>optional bytes provider_session_token = 6;</code>
   * @return The providerSessionToken.
   */
  com.google.protobuf.ByteString getProviderSessionToken();
}
