// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface LicenseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:License)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .LicenseIdentification id = 1;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional .LicenseIdentification id = 1;</code>
   * @return The id.
   */
  de.klassenserver7b.widevine4j.protobuf.LicenseIdentification getId();
  /**
   * <code>optional .LicenseIdentification id = 1;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.LicenseIdentificationOrBuilder getIdOrBuilder();

  /**
   * <code>optional .License.Policy policy = 2;</code>
   * @return Whether the policy field is set.
   */
  boolean hasPolicy();
  /**
   * <code>optional .License.Policy policy = 2;</code>
   * @return The policy.
   */
  de.klassenserver7b.widevine4j.protobuf.License.Policy getPolicy();
  /**
   * <code>optional .License.Policy policy = 2;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.License.PolicyOrBuilder getPolicyOrBuilder();

  /**
   * <code>repeated .License.KeyContainer key = 3;</code>
   */
  java.util.List<de.klassenserver7b.widevine4j.protobuf.License.KeyContainer> 
      getKeyList();
  /**
   * <code>repeated .License.KeyContainer key = 3;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.License.KeyContainer getKey(int index);
  /**
   * <code>repeated .License.KeyContainer key = 3;</code>
   */
  int getKeyCount();
  /**
   * <code>repeated .License.KeyContainer key = 3;</code>
   */
  java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.License.KeyContainerOrBuilder> 
      getKeyOrBuilderList();
  /**
   * <code>repeated .License.KeyContainer key = 3;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.License.KeyContainerOrBuilder getKeyOrBuilder(
      int index);

  /**
   * <pre>
   * Time of the request in seconds (UTC) as set in
   * LicenseRequest.request_time.  If this time is not set in the request,
   * the local time at the license service is used in this field.
   * </pre>
   *
   * <code>optional int64 license_start_time = 4;</code>
   * @return Whether the licenseStartTime field is set.
   */
  boolean hasLicenseStartTime();
  /**
   * <pre>
   * Time of the request in seconds (UTC) as set in
   * LicenseRequest.request_time.  If this time is not set in the request,
   * the local time at the license service is used in this field.
   * </pre>
   *
   * <code>optional int64 license_start_time = 4;</code>
   * @return The licenseStartTime.
   */
  long getLicenseStartTime();

  /**
   * <code>optional bool remote_attestation_verified = 5 [default = false];</code>
   * @return Whether the remoteAttestationVerified field is set.
   */
  boolean hasRemoteAttestationVerified();
  /**
   * <code>optional bool remote_attestation_verified = 5 [default = false];</code>
   * @return The remoteAttestationVerified.
   */
  boolean getRemoteAttestationVerified();

  /**
   * <pre>
   * Client token generated by the content provider. Optional.
   * </pre>
   *
   * <code>optional bytes provider_client_token = 6;</code>
   * @return Whether the providerClientToken field is set.
   */
  boolean hasProviderClientToken();
  /**
   * <pre>
   * Client token generated by the content provider. Optional.
   * </pre>
   *
   * <code>optional bytes provider_client_token = 6;</code>
   * @return The providerClientToken.
   */
  com.google.protobuf.ByteString getProviderClientToken();

  /**
   * <pre>
   * 4cc code specifying the CENC protection scheme as defined in the CENC 3.0
   * specification. Propagated from Widevine PSSH box. Optional.
   * </pre>
   *
   * <code>optional uint32 protection_scheme = 7;</code>
   * @return Whether the protectionScheme field is set.
   */
  boolean hasProtectionScheme();
  /**
   * <pre>
   * 4cc code specifying the CENC protection scheme as defined in the CENC 3.0
   * specification. Propagated from Widevine PSSH box. Optional.
   * </pre>
   *
   * <code>optional uint32 protection_scheme = 7;</code>
   * @return The protectionScheme.
   */
  int getProtectionScheme();

  /**
   * <pre>
   * 8 byte verification field "HDCPDATA" followed by unsigned 32 bit minimum
   * HDCP SRM version (whether the version is for HDCP1 SRM or HDCP2 SRM
   * depends on client max_hdcp_version).
   * Additional details can be found in Widevine Modular DRM Security
   * Integration Guide for CENC.
   * </pre>
   *
   * <code>optional bytes srm_requirement = 8;</code>
   * @return Whether the srmRequirement field is set.
   */
  boolean hasSrmRequirement();
  /**
   * <pre>
   * 8 byte verification field "HDCPDATA" followed by unsigned 32 bit minimum
   * HDCP SRM version (whether the version is for HDCP1 SRM or HDCP2 SRM
   * depends on client max_hdcp_version).
   * Additional details can be found in Widevine Modular DRM Security
   * Integration Guide for CENC.
   * </pre>
   *
   * <code>optional bytes srm_requirement = 8;</code>
   * @return The srmRequirement.
   */
  com.google.protobuf.ByteString getSrmRequirement();

  /**
   * <pre>
   * If present this contains a signed SRM file (either HDCP1 SRM or HDCP2 SRM
   * depending on client max_hdcp_version) that should be installed on the
   * client device.
   * </pre>
   *
   * <code>optional bytes srm_update = 9;</code>
   * @return Whether the srmUpdate field is set.
   */
  boolean hasSrmUpdate();
  /**
   * <pre>
   * If present this contains a signed SRM file (either HDCP1 SRM or HDCP2 SRM
   * depending on client max_hdcp_version) that should be installed on the
   * client device.
   * </pre>
   *
   * <code>optional bytes srm_update = 9;</code>
   * @return The srmUpdate.
   */
  com.google.protobuf.ByteString getSrmUpdate();

  /**
   * <pre>
   * Indicates the status of any type of platform verification performed by the
   * server.
   * </pre>
   *
   * <code>optional .PlatformVerificationStatus platform_verification_status = 10 [default = PLATFORM_NO_VERIFICATION];</code>
   * @return Whether the platformVerificationStatus field is set.
   */
  boolean hasPlatformVerificationStatus();
  /**
   * <pre>
   * Indicates the status of any type of platform verification performed by the
   * server.
   * </pre>
   *
   * <code>optional .PlatformVerificationStatus platform_verification_status = 10 [default = PLATFORM_NO_VERIFICATION];</code>
   * @return The platformVerificationStatus.
   */
  de.klassenserver7b.widevine4j.protobuf.PlatformVerificationStatus getPlatformVerificationStatus();

  /**
   * <pre>
   * IDs of the groups for which keys are delivered in this license, if any.
   * </pre>
   *
   * <code>repeated bytes group_ids = 11;</code>
   * @return A list containing the groupIds.
   */
  java.util.List<com.google.protobuf.ByteString> getGroupIdsList();
  /**
   * <pre>
   * IDs of the groups for which keys are delivered in this license, if any.
   * </pre>
   *
   * <code>repeated bytes group_ids = 11;</code>
   * @return The count of groupIds.
   */
  int getGroupIdsCount();
  /**
   * <pre>
   * IDs of the groups for which keys are delivered in this license, if any.
   * </pre>
   *
   * <code>repeated bytes group_ids = 11;</code>
   * @param index The index of the element to return.
   * @return The groupIds at the given index.
   */
  com.google.protobuf.ByteString getGroupIds(int index);
}
