// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * Protobuf enum {@code LicenseType}
 */
public enum LicenseType
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>STREAMING = 1;</code>
   */
  STREAMING(1),
  /**
   * <code>OFFLINE = 2;</code>
   */
  OFFLINE(2),
  /**
   * <pre>
   * License type decision is left to provider.
   * </pre>
   *
   * <code>AUTOMATIC = 3;</code>
   */
  AUTOMATIC(3),
  ;

  /**
   * <code>STREAMING = 1;</code>
   */
  public static final int STREAMING_VALUE = 1;
  /**
   * <code>OFFLINE = 2;</code>
   */
  public static final int OFFLINE_VALUE = 2;
  /**
   * <pre>
   * License type decision is left to provider.
   * </pre>
   *
   * <code>AUTOMATIC = 3;</code>
   */
  public static final int AUTOMATIC_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static LicenseType valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static LicenseType forNumber(int value) {
    switch (value) {
      case 1: return STREAMING;
      case 2: return OFFLINE;
      case 3: return AUTOMATIC;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<LicenseType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      LicenseType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<LicenseType>() {
          public LicenseType findValueByNumber(int number) {
            return LicenseType.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.getDescriptor().getEnumTypes().get(0);
  }

  private static final LicenseType[] VALUES = values();

  public static LicenseType valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private LicenseType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:LicenseType)
}

