// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * <pre>
 * LicenseIdentification is propagated from LicenseRequest to License,
 * incrementing version with each iteration.
 * </pre>
 *
 * Protobuf type {@code LicenseIdentification}
 */
public final class LicenseIdentification extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:LicenseIdentification)
    LicenseIdentificationOrBuilder {
private static final long serialVersionUID = 0L;
  // Use LicenseIdentification.newBuilder() to construct.
  private LicenseIdentification(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private LicenseIdentification() {
    requestId_ = com.google.protobuf.ByteString.EMPTY;
    sessionId_ = com.google.protobuf.ByteString.EMPTY;
    purchaseId_ = com.google.protobuf.ByteString.EMPTY;
    type_ = 1;
    providerSessionToken_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new LicenseIdentification();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_LicenseIdentification_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_LicenseIdentification_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.klassenserver7b.widevine4j.protobuf.LicenseIdentification.class, de.klassenserver7b.widevine4j.protobuf.LicenseIdentification.Builder.class);
  }

  private int bitField0_;
  public static final int REQUEST_ID_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString requestId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes request_id = 1;</code>
   * @return Whether the requestId field is set.
   */
  @java.lang.Override
  public boolean hasRequestId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional bytes request_id = 1;</code>
   * @return The requestId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRequestId() {
    return requestId_;
  }

  public static final int SESSION_ID_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString sessionId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes session_id = 2;</code>
   * @return Whether the sessionId field is set.
   */
  @java.lang.Override
  public boolean hasSessionId() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes session_id = 2;</code>
   * @return The sessionId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSessionId() {
    return sessionId_;
  }

  public static final int PURCHASE_ID_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString purchaseId_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes purchase_id = 3;</code>
   * @return Whether the purchaseId field is set.
   */
  @java.lang.Override
  public boolean hasPurchaseId() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>optional bytes purchase_id = 3;</code>
   * @return The purchaseId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getPurchaseId() {
    return purchaseId_;
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private int type_ = 1;
  /**
   * <code>optional .LicenseType type = 4;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override public boolean hasType() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>optional .LicenseType type = 4;</code>
   * @return The type.
   */
  @java.lang.Override public de.klassenserver7b.widevine4j.protobuf.LicenseType getType() {
    de.klassenserver7b.widevine4j.protobuf.LicenseType result = de.klassenserver7b.widevine4j.protobuf.LicenseType.forNumber(type_);
    return result == null ? de.klassenserver7b.widevine4j.protobuf.LicenseType.STREAMING : result;
  }

  public static final int VERSION_FIELD_NUMBER = 5;
  private int version_ = 0;
  /**
   * <code>optional int32 version = 5;</code>
   * @return Whether the version field is set.
   */
  @java.lang.Override
  public boolean hasVersion() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>optional int32 version = 5;</code>
   * @return The version.
   */
  @java.lang.Override
  public int getVersion() {
    return version_;
  }

  public static final int PROVIDER_SESSION_TOKEN_FIELD_NUMBER = 6;
  private com.google.protobuf.ByteString providerSessionToken_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes provider_session_token = 6;</code>
   * @return Whether the providerSessionToken field is set.
   */
  @java.lang.Override
  public boolean hasProviderSessionToken() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <code>optional bytes provider_session_token = 6;</code>
   * @return The providerSessionToken.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getProviderSessionToken() {
    return providerSessionToken_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(1, requestId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, sessionId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, purchaseId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, type_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeInt32(5, version_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeBytes(6, providerSessionToken_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, requestId_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, sessionId_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, purchaseId_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, type_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, version_);
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(6, providerSessionToken_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.LicenseIdentification)) {
      return super.equals(obj);
    }
    de.klassenserver7b.widevine4j.protobuf.LicenseIdentification other = (de.klassenserver7b.widevine4j.protobuf.LicenseIdentification) obj;

    if (hasRequestId() != other.hasRequestId()) return false;
    if (hasRequestId()) {
      if (!getRequestId()
          .equals(other.getRequestId())) return false;
    }
    if (hasSessionId() != other.hasSessionId()) return false;
    if (hasSessionId()) {
      if (!getSessionId()
          .equals(other.getSessionId())) return false;
    }
    if (hasPurchaseId() != other.hasPurchaseId()) return false;
    if (hasPurchaseId()) {
      if (!getPurchaseId()
          .equals(other.getPurchaseId())) return false;
    }
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (hasVersion() != other.hasVersion()) return false;
    if (hasVersion()) {
      if (getVersion()
          != other.getVersion()) return false;
    }
    if (hasProviderSessionToken() != other.hasProviderSessionToken()) return false;
    if (hasProviderSessionToken()) {
      if (!getProviderSessionToken()
          .equals(other.getProviderSessionToken())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasRequestId()) {
      hash = (37 * hash) + REQUEST_ID_FIELD_NUMBER;
      hash = (53 * hash) + getRequestId().hashCode();
    }
    if (hasSessionId()) {
      hash = (37 * hash) + SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSessionId().hashCode();
    }
    if (hasPurchaseId()) {
      hash = (37 * hash) + PURCHASE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getPurchaseId().hashCode();
    }
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    if (hasVersion()) {
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion();
    }
    if (hasProviderSessionToken()) {
      hash = (37 * hash) + PROVIDER_SESSION_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getProviderSessionToken().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.LicenseIdentification prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * LicenseIdentification is propagated from LicenseRequest to License,
   * incrementing version with each iteration.
   * </pre>
   *
   * Protobuf type {@code LicenseIdentification}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:LicenseIdentification)
      de.klassenserver7b.widevine4j.protobuf.LicenseIdentificationOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_LicenseIdentification_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_LicenseIdentification_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.LicenseIdentification.class, de.klassenserver7b.widevine4j.protobuf.LicenseIdentification.Builder.class);
    }

    // Construct using de.klassenserver7b.widevine4j.protobuf.LicenseIdentification.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      requestId_ = com.google.protobuf.ByteString.EMPTY;
      sessionId_ = com.google.protobuf.ByteString.EMPTY;
      purchaseId_ = com.google.protobuf.ByteString.EMPTY;
      type_ = 1;
      version_ = 0;
      providerSessionToken_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_LicenseIdentification_descriptor;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.LicenseIdentification getDefaultInstanceForType() {
      return de.klassenserver7b.widevine4j.protobuf.LicenseIdentification.getDefaultInstance();
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.LicenseIdentification build() {
      de.klassenserver7b.widevine4j.protobuf.LicenseIdentification result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.LicenseIdentification buildPartial() {
      de.klassenserver7b.widevine4j.protobuf.LicenseIdentification result = new de.klassenserver7b.widevine4j.protobuf.LicenseIdentification(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.LicenseIdentification result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.requestId_ = requestId_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sessionId_ = sessionId_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.purchaseId_ = purchaseId_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.version_ = version_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.providerSessionToken_ = providerSessionToken_;
        to_bitField0_ |= 0x00000020;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.klassenserver7b.widevine4j.protobuf.LicenseIdentification) {
        return mergeFrom((de.klassenserver7b.widevine4j.protobuf.LicenseIdentification)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.LicenseIdentification other) {
      if (other == de.klassenserver7b.widevine4j.protobuf.LicenseIdentification.getDefaultInstance()) return this;
      if (other.hasRequestId()) {
        setRequestId(other.getRequestId());
      }
      if (other.hasSessionId()) {
        setSessionId(other.getSessionId());
      }
      if (other.hasPurchaseId()) {
        setPurchaseId(other.getPurchaseId());
      }
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasVersion()) {
        setVersion(other.getVersion());
      }
      if (other.hasProviderSessionToken()) {
        setProviderSessionToken(other.getProviderSessionToken());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              requestId_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              sessionId_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              purchaseId_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              int tmpRaw = input.readEnum();
              de.klassenserver7b.widevine4j.protobuf.LicenseType tmpValue =
                  de.klassenserver7b.widevine4j.protobuf.LicenseType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(4, tmpRaw);
              } else {
                type_ = tmpRaw;
                bitField0_ |= 0x00000008;
              }
              break;
            } // case 32
            case 40: {
              version_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 50: {
              providerSessionToken_ = input.readBytes();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString requestId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes request_id = 1;</code>
     * @return Whether the requestId field is set.
     */
    @java.lang.Override
    public boolean hasRequestId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional bytes request_id = 1;</code>
     * @return The requestId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRequestId() {
      return requestId_;
    }
    /**
     * <code>optional bytes request_id = 1;</code>
     * @param value The requestId to set.
     * @return This builder for chaining.
     */
    public Builder setRequestId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      requestId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes request_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRequestId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      requestId_ = getDefaultInstance().getRequestId();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString sessionId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes session_id = 2;</code>
     * @return Whether the sessionId field is set.
     */
    @java.lang.Override
    public boolean hasSessionId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes session_id = 2;</code>
     * @return The sessionId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionId() {
      return sessionId_;
    }
    /**
     * <code>optional bytes session_id = 2;</code>
     * @param value The sessionId to set.
     * @return This builder for chaining.
     */
    public Builder setSessionId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      sessionId_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes session_id = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionId() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sessionId_ = getDefaultInstance().getSessionId();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString purchaseId_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes purchase_id = 3;</code>
     * @return Whether the purchaseId field is set.
     */
    @java.lang.Override
    public boolean hasPurchaseId() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional bytes purchase_id = 3;</code>
     * @return The purchaseId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPurchaseId() {
      return purchaseId_;
    }
    /**
     * <code>optional bytes purchase_id = 3;</code>
     * @param value The purchaseId to set.
     * @return This builder for chaining.
     */
    public Builder setPurchaseId(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      purchaseId_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes purchase_id = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPurchaseId() {
      bitField0_ = (bitField0_ & ~0x00000004);
      purchaseId_ = getDefaultInstance().getPurchaseId();
      onChanged();
      return this;
    }

    private int type_ = 1;
    /**
     * <code>optional .LicenseType type = 4;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional .LicenseType type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.LicenseType getType() {
      de.klassenserver7b.widevine4j.protobuf.LicenseType result = de.klassenserver7b.widevine4j.protobuf.LicenseType.forNumber(type_);
      return result == null ? de.klassenserver7b.widevine4j.protobuf.LicenseType.STREAMING : result;
    }
    /**
     * <code>optional .LicenseType type = 4;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(de.klassenserver7b.widevine4j.protobuf.LicenseType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .LicenseType type = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000008);
      type_ = 1;
      onChanged();
      return this;
    }

    private int version_ ;
    /**
     * <code>optional int32 version = 5;</code>
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional int32 version = 5;</code>
     * @return The version.
     */
    @java.lang.Override
    public int getVersion() {
      return version_;
    }
    /**
     * <code>optional int32 version = 5;</code>
     * @param value The version to set.
     * @return This builder for chaining.
     */
    public Builder setVersion(int value) {

      version_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>optional int32 version = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000010);
      version_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString providerSessionToken_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes provider_session_token = 6;</code>
     * @return Whether the providerSessionToken field is set.
     */
    @java.lang.Override
    public boolean hasProviderSessionToken() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional bytes provider_session_token = 6;</code>
     * @return The providerSessionToken.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getProviderSessionToken() {
      return providerSessionToken_;
    }
    /**
     * <code>optional bytes provider_session_token = 6;</code>
     * @param value The providerSessionToken to set.
     * @return This builder for chaining.
     */
    public Builder setProviderSessionToken(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      providerSessionToken_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes provider_session_token = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearProviderSessionToken() {
      bitField0_ = (bitField0_ & ~0x00000020);
      providerSessionToken_ = getDefaultInstance().getProviderSessionToken();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:LicenseIdentification)
  }

  // @@protoc_insertion_point(class_scope:LicenseIdentification)
  private static final de.klassenserver7b.widevine4j.protobuf.LicenseIdentification DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.LicenseIdentification();
  }

  public static de.klassenserver7b.widevine4j.protobuf.LicenseIdentification getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<LicenseIdentification>
      PARSER = new com.google.protobuf.AbstractParser<LicenseIdentification>() {
    @java.lang.Override
    public LicenseIdentification parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<LicenseIdentification> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<LicenseIdentification> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.LicenseIdentification getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

