// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * Protobuf type {@code MetricData}
 */
public final class MetricData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:MetricData)
    MetricDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use MetricData.newBuilder() to construct.
  private MetricData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private MetricData() {
    stageName_ = "";
    metricData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new MetricData();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.klassenserver7b.widevine4j.protobuf.MetricData.class, de.klassenserver7b.widevine4j.protobuf.MetricData.Builder.class);
  }

  /**
   * Protobuf enum {@code MetricData.MetricType}
   */
  public enum MetricType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * The time spent in the 'stage', specified in microseconds.
     * </pre>
     *
     * <code>LATENCY = 1;</code>
     */
    LATENCY(1),
    /**
     * <pre>
     * The UNIX epoch timestamp at which the 'stage' was first accessed in
     * microseconds.
     * </pre>
     *
     * <code>TIMESTAMP = 2;</code>
     */
    TIMESTAMP(2),
    ;

    /**
     * <pre>
     * The time spent in the 'stage', specified in microseconds.
     * </pre>
     *
     * <code>LATENCY = 1;</code>
     */
    public static final int LATENCY_VALUE = 1;
    /**
     * <pre>
     * The UNIX epoch timestamp at which the 'stage' was first accessed in
     * microseconds.
     * </pre>
     *
     * <code>TIMESTAMP = 2;</code>
     */
    public static final int TIMESTAMP_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MetricType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MetricType forNumber(int value) {
      switch (value) {
        case 1: return LATENCY;
        case 2: return TIMESTAMP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MetricType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MetricType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MetricType>() {
            public MetricType findValueByNumber(int number) {
              return MetricType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.MetricData.getDescriptor().getEnumTypes().get(0);
    }

    private static final MetricType[] VALUES = values();

    public static MetricType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MetricType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:MetricData.MetricType)
  }

  public interface TypeValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MetricData.TypeValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .MetricData.MetricType type = 1;</code>
     * @return Whether the type field is set.
     */
    boolean hasType();
    /**
     * <code>optional .MetricData.MetricType type = 1;</code>
     * @return The type.
     */
    de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType getType();

    /**
     * <pre>
     * The value associated with 'type'.  For example if type == LATENCY, the
     * value would be the time in microseconds spent in this 'stage'.
     * </pre>
     *
     * <code>optional int64 value = 2 [default = 0];</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <pre>
     * The value associated with 'type'.  For example if type == LATENCY, the
     * value would be the time in microseconds spent in this 'stage'.
     * </pre>
     *
     * <code>optional int64 value = 2 [default = 0];</code>
     * @return The value.
     */
    long getValue();
  }
  /**
   * Protobuf type {@code MetricData.TypeValue}
   */
  public static final class TypeValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MetricData.TypeValue)
      TypeValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TypeValue.newBuilder() to construct.
    private TypeValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TypeValue() {
      type_ = 1;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TypeValue();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_TypeValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_TypeValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.class, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 1;
    /**
     * <code>optional .MetricData.MetricType type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .MetricData.MetricType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override public de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType getType() {
      de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType result = de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType.forNumber(type_);
      return result == null ? de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType.LATENCY : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private long value_ = 0L;
    /**
     * <pre>
     * The value associated with 'type'.  For example if type == LATENCY, the
     * value would be the time in microseconds spent in this 'stage'.
     * </pre>
     *
     * <code>optional int64 value = 2 [default = 0];</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * The value associated with 'type'.  For example if type == LATENCY, the
     * value would be the time in microseconds spent in this 'stage'.
     * </pre>
     *
     * <code>optional int64 value = 2 [default = 0];</code>
     * @return The value.
     */
    @java.lang.Override
    public long getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt64(2, value_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, value_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue)) {
        return super.equals(obj);
      }
      de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue other = (de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue) obj;

      if (hasType() != other.hasType()) return false;
      if (hasType()) {
        if (type_ != other.type_) return false;
      }
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (getValue()
            != other.getValue()) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + type_;
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getValue());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MetricData.TypeValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MetricData.TypeValue)
        de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_TypeValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_TypeValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.class, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder.class);
      }

      // Construct using de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 1;
        value_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_TypeValue_descriptor;
      }

      @java.lang.Override
      public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue getDefaultInstanceForType() {
        return de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.getDefaultInstance();
      }

      @java.lang.Override
      public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue build() {
        de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue buildPartial() {
        de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue result = new de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.value_ = value_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue) {
          return mergeFrom((de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue other) {
        if (other == de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                int tmpRaw = input.readEnum();
                de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType tmpValue =
                    de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType.forNumber(tmpRaw);
                if (tmpValue == null) {
                  mergeUnknownVarintField(1, tmpRaw);
                } else {
                  type_ = tmpRaw;
                  bitField0_ |= 0x00000001;
                }
                break;
              } // case 8
              case 16: {
                value_ = input.readInt64();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 1;
      /**
       * <code>optional .MetricData.MetricType type = 1;</code>
       * @return Whether the type field is set.
       */
      @java.lang.Override public boolean hasType() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional .MetricData.MetricType type = 1;</code>
       * @return The type.
       */
      @java.lang.Override
      public de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType getType() {
        de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType result = de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType.forNumber(type_);
        return result == null ? de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType.LATENCY : result;
      }
      /**
       * <code>optional .MetricData.MetricType type = 1;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(de.klassenserver7b.widevine4j.protobuf.MetricData.MetricType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .MetricData.MetricType type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 1;
        onChanged();
        return this;
      }

      private long value_ ;
      /**
       * <pre>
       * The value associated with 'type'.  For example if type == LATENCY, the
       * value would be the time in microseconds spent in this 'stage'.
       * </pre>
       *
       * <code>optional int64 value = 2 [default = 0];</code>
       * @return Whether the value field is set.
       */
      @java.lang.Override
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * The value associated with 'type'.  For example if type == LATENCY, the
       * value would be the time in microseconds spent in this 'stage'.
       * </pre>
       *
       * <code>optional int64 value = 2 [default = 0];</code>
       * @return The value.
       */
      @java.lang.Override
      public long getValue() {
        return value_;
      }
      /**
       * <pre>
       * The value associated with 'type'.  For example if type == LATENCY, the
       * value would be the time in microseconds spent in this 'stage'.
       * </pre>
       *
       * <code>optional int64 value = 2 [default = 0];</code>
       * @param value The value to set.
       * @return This builder for chaining.
       */
      public Builder setValue(long value) {

        value_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The value associated with 'type'.  For example if type == LATENCY, the
       * value would be the time in microseconds spent in this 'stage'.
       * </pre>
       *
       * <code>optional int64 value = 2 [default = 0];</code>
       * @return This builder for chaining.
       */
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MetricData.TypeValue)
    }

    // @@protoc_insertion_point(class_scope:MetricData.TypeValue)
    private static final de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue();
    }

    public static de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TypeValue>
        PARSER = new com.google.protobuf.AbstractParser<TypeValue>() {
      @java.lang.Override
      public TypeValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TypeValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TypeValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int STAGE_NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object stageName_ = "";
  /**
   * <pre>
   * 'stage' that is currently processing the SignedMessage.  Required.
   * </pre>
   *
   * <code>optional string stage_name = 1;</code>
   * @return Whether the stageName field is set.
   */
  @java.lang.Override
  public boolean hasStageName() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * 'stage' that is currently processing the SignedMessage.  Required.
   * </pre>
   *
   * <code>optional string stage_name = 1;</code>
   * @return The stageName.
   */
  @java.lang.Override
  public java.lang.String getStageName() {
    java.lang.Object ref = stageName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        stageName_ = s;
      }
      return s;
    }
  }
  /**
   * <pre>
   * 'stage' that is currently processing the SignedMessage.  Required.
   * </pre>
   *
   * <code>optional string stage_name = 1;</code>
   * @return The bytes for stageName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getStageNameBytes() {
    java.lang.Object ref = stageName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      stageName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METRIC_DATA_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue> metricData_;
  /**
   * <pre>
   * metric and associated value.
   * </pre>
   *
   * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
   */
  @java.lang.Override
  public java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue> getMetricDataList() {
    return metricData_;
  }
  /**
   * <pre>
   * metric and associated value.
   * </pre>
   *
   * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder> 
      getMetricDataOrBuilderList() {
    return metricData_;
  }
  /**
   * <pre>
   * metric and associated value.
   * </pre>
   *
   * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
   */
  @java.lang.Override
  public int getMetricDataCount() {
    return metricData_.size();
  }
  /**
   * <pre>
   * metric and associated value.
   * </pre>
   *
   * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue getMetricData(int index) {
    return metricData_.get(index);
  }
  /**
   * <pre>
   * metric and associated value.
   * </pre>
   *
   * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder getMetricDataOrBuilder(
      int index) {
    return metricData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, stageName_);
    }
    for (int i = 0; i < metricData_.size(); i++) {
      output.writeMessage(2, metricData_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, stageName_);
    }
    for (int i = 0; i < metricData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, metricData_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.MetricData)) {
      return super.equals(obj);
    }
    de.klassenserver7b.widevine4j.protobuf.MetricData other = (de.klassenserver7b.widevine4j.protobuf.MetricData) obj;

    if (hasStageName() != other.hasStageName()) return false;
    if (hasStageName()) {
      if (!getStageName()
          .equals(other.getStageName())) return false;
    }
    if (!getMetricDataList()
        .equals(other.getMetricDataList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStageName()) {
      hash = (37 * hash) + STAGE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getStageName().hashCode();
    }
    if (getMetricDataCount() > 0) {
      hash = (37 * hash) + METRIC_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetricDataList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.MetricData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.MetricData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code MetricData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:MetricData)
      de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.MetricData.class, de.klassenserver7b.widevine4j.protobuf.MetricData.Builder.class);
    }

    // Construct using de.klassenserver7b.widevine4j.protobuf.MetricData.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      stageName_ = "";
      if (metricDataBuilder_ == null) {
        metricData_ = java.util.Collections.emptyList();
      } else {
        metricData_ = null;
        metricDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_MetricData_descriptor;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.MetricData getDefaultInstanceForType() {
      return de.klassenserver7b.widevine4j.protobuf.MetricData.getDefaultInstance();
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.MetricData build() {
      de.klassenserver7b.widevine4j.protobuf.MetricData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.MetricData buildPartial() {
      de.klassenserver7b.widevine4j.protobuf.MetricData result = new de.klassenserver7b.widevine4j.protobuf.MetricData(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(de.klassenserver7b.widevine4j.protobuf.MetricData result) {
      if (metricDataBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          metricData_ = java.util.Collections.unmodifiableList(metricData_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.metricData_ = metricData_;
      } else {
        result.metricData_ = metricDataBuilder_.build();
      }
    }

    private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.MetricData result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.stageName_ = stageName_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.klassenserver7b.widevine4j.protobuf.MetricData) {
        return mergeFrom((de.klassenserver7b.widevine4j.protobuf.MetricData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.MetricData other) {
      if (other == de.klassenserver7b.widevine4j.protobuf.MetricData.getDefaultInstance()) return this;
      if (other.hasStageName()) {
        stageName_ = other.stageName_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (metricDataBuilder_ == null) {
        if (!other.metricData_.isEmpty()) {
          if (metricData_.isEmpty()) {
            metricData_ = other.metricData_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureMetricDataIsMutable();
            metricData_.addAll(other.metricData_);
          }
          onChanged();
        }
      } else {
        if (!other.metricData_.isEmpty()) {
          if (metricDataBuilder_.isEmpty()) {
            metricDataBuilder_.dispose();
            metricDataBuilder_ = null;
            metricData_ = other.metricData_;
            bitField0_ = (bitField0_ & ~0x00000002);
            metricDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetricDataFieldBuilder() : null;
          } else {
            metricDataBuilder_.addAllMessages(other.metricData_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              stageName_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue m =
                  input.readMessage(
                      de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.PARSER,
                      extensionRegistry);
              if (metricDataBuilder_ == null) {
                ensureMetricDataIsMutable();
                metricData_.add(m);
              } else {
                metricDataBuilder_.addMessage(m);
              }
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object stageName_ = "";
    /**
     * <pre>
     * 'stage' that is currently processing the SignedMessage.  Required.
     * </pre>
     *
     * <code>optional string stage_name = 1;</code>
     * @return Whether the stageName field is set.
     */
    public boolean hasStageName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * 'stage' that is currently processing the SignedMessage.  Required.
     * </pre>
     *
     * <code>optional string stage_name = 1;</code>
     * @return The stageName.
     */
    public java.lang.String getStageName() {
      java.lang.Object ref = stageName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          stageName_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 'stage' that is currently processing the SignedMessage.  Required.
     * </pre>
     *
     * <code>optional string stage_name = 1;</code>
     * @return The bytes for stageName.
     */
    public com.google.protobuf.ByteString
        getStageNameBytes() {
      java.lang.Object ref = stageName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        stageName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 'stage' that is currently processing the SignedMessage.  Required.
     * </pre>
     *
     * <code>optional string stage_name = 1;</code>
     * @param value The stageName to set.
     * @return This builder for chaining.
     */
    public Builder setStageName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      stageName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 'stage' that is currently processing the SignedMessage.  Required.
     * </pre>
     *
     * <code>optional string stage_name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearStageName() {
      stageName_ = getDefaultInstance().getStageName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 'stage' that is currently processing the SignedMessage.  Required.
     * </pre>
     *
     * <code>optional string stage_name = 1;</code>
     * @param value The bytes for stageName to set.
     * @return This builder for chaining.
     */
    public Builder setStageNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      stageName_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue> metricData_ =
      java.util.Collections.emptyList();
    private void ensureMetricDataIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        metricData_ = new java.util.ArrayList<de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue>(metricData_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder> metricDataBuilder_;

    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue> getMetricDataList() {
      if (metricDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metricData_);
      } else {
        return metricDataBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public int getMetricDataCount() {
      if (metricDataBuilder_ == null) {
        return metricData_.size();
      } else {
        return metricDataBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue getMetricData(int index) {
      if (metricDataBuilder_ == null) {
        return metricData_.get(index);
      } else {
        return metricDataBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder setMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue value) {
      if (metricDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricDataIsMutable();
        metricData_.set(index, value);
        onChanged();
      } else {
        metricDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder setMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder builderForValue) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.set(index, builderForValue.build());
        onChanged();
      } else {
        metricDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder addMetricData(de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue value) {
      if (metricDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricDataIsMutable();
        metricData_.add(value);
        onChanged();
      } else {
        metricDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder addMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue value) {
      if (metricDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricDataIsMutable();
        metricData_.add(index, value);
        onChanged();
      } else {
        metricDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder addMetricData(
        de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder builderForValue) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.add(builderForValue.build());
        onChanged();
      } else {
        metricDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder addMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder builderForValue) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.add(index, builderForValue.build());
        onChanged();
      } else {
        metricDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder addAllMetricData(
        java.lang.Iterable<? extends de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue> values) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metricData_);
        onChanged();
      } else {
        metricDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder clearMetricData() {
      if (metricDataBuilder_ == null) {
        metricData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        metricDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public Builder removeMetricData(int index) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.remove(index);
        onChanged();
      } else {
        metricDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder getMetricDataBuilder(
        int index) {
      return getMetricDataFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder getMetricDataOrBuilder(
        int index) {
      if (metricDataBuilder_ == null) {
        return metricData_.get(index);  } else {
        return metricDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder> 
         getMetricDataOrBuilderList() {
      if (metricDataBuilder_ != null) {
        return metricDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metricData_);
      }
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder addMetricDataBuilder() {
      return getMetricDataFieldBuilder().addBuilder(
          de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.getDefaultInstance());
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder addMetricDataBuilder(
        int index) {
      return getMetricDataFieldBuilder().addBuilder(
          index, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.getDefaultInstance());
    }
    /**
     * <pre>
     * metric and associated value.
     * </pre>
     *
     * <code>repeated .MetricData.TypeValue metric_data = 2;</code>
     */
    public java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder> 
         getMetricDataBuilderList() {
      return getMetricDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder> 
        getMetricDataFieldBuilder() {
      if (metricDataBuilder_ == null) {
        metricDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValue.Builder, de.klassenserver7b.widevine4j.protobuf.MetricData.TypeValueOrBuilder>(
                metricData_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        metricData_ = null;
      }
      return metricDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:MetricData)
  }

  // @@protoc_insertion_point(class_scope:MetricData)
  private static final de.klassenserver7b.widevine4j.protobuf.MetricData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.MetricData();
  }

  public static de.klassenserver7b.widevine4j.protobuf.MetricData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<MetricData>
      PARSER = new com.google.protobuf.AbstractParser<MetricData>() {
    @java.lang.Override
    public MetricData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<MetricData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<MetricData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.MetricData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

