// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * Protobuf enum {@code ProtocolVersion}
 */
public enum ProtocolVersion
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>VERSION_2_0 = 20;</code>
   */
  VERSION_2_0(20),
  /**
   * <code>VERSION_2_1 = 21;</code>
   */
  VERSION_2_1(21),
  /**
   * <code>VERSION_2_2 = 22;</code>
   */
  VERSION_2_2(22),
  ;

  /**
   * <code>VERSION_2_0 = 20;</code>
   */
  public static final int VERSION_2_0_VALUE = 20;
  /**
   * <code>VERSION_2_1 = 21;</code>
   */
  public static final int VERSION_2_1_VALUE = 21;
  /**
   * <code>VERSION_2_2 = 22;</code>
   */
  public static final int VERSION_2_2_VALUE = 22;


  public final int getNumber() {
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ProtocolVersion valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static ProtocolVersion forNumber(int value) {
    switch (value) {
      case 20: return VERSION_2_0;
      case 21: return VERSION_2_1;
      case 22: return VERSION_2_2;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ProtocolVersion>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ProtocolVersion> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ProtocolVersion>() {
          public ProtocolVersion findValueByNumber(int number) {
            return ProtocolVersion.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    return getDescriptor().getValues().get(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.getDescriptor().getEnumTypes().get(2);
  }

  private static final ProtocolVersion[] VALUES = values();

  public static ProtocolVersion valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private ProtocolVersion(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:ProtocolVersion)
}

