// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface SignedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignedMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .SignedMessage.MessageType type = 1;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <code>optional .SignedMessage.MessageType type = 1;</code>
   * @return The type.
   */
  de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType getType();

  /**
   * <code>optional bytes msg = 2;</code>
   * @return Whether the msg field is set.
   */
  boolean hasMsg();
  /**
   * <code>optional bytes msg = 2;</code>
   * @return The msg.
   */
  com.google.protobuf.ByteString getMsg();

  /**
   * <pre>
   * Required field that contains the signature of the bytes of msg.
   * For license requests, the signing algorithm is determined by the
   * certificate contained in the request.
   * For license responses, the signing algorithm is HMAC with signing key based
   * on |session_key|.
   * </pre>
   *
   * <code>optional bytes signature = 3;</code>
   * @return Whether the signature field is set.
   */
  boolean hasSignature();
  /**
   * <pre>
   * Required field that contains the signature of the bytes of msg.
   * For license requests, the signing algorithm is determined by the
   * certificate contained in the request.
   * For license responses, the signing algorithm is HMAC with signing key based
   * on |session_key|.
   * </pre>
   *
   * <code>optional bytes signature = 3;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <pre>
   * If populated, the contents of this field will be signaled by the
   * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
   * key is the bytes of an encrypted AES key. If the |session_key_type| is
   * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
   * serialized ECC public key.
   * </pre>
   *
   * <code>optional bytes session_key = 4;</code>
   * @return Whether the sessionKey field is set.
   */
  boolean hasSessionKey();
  /**
   * <pre>
   * If populated, the contents of this field will be signaled by the
   * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
   * key is the bytes of an encrypted AES key. If the |session_key_type| is
   * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
   * serialized ECC public key.
   * </pre>
   *
   * <code>optional bytes session_key = 4;</code>
   * @return The sessionKey.
   */
  com.google.protobuf.ByteString getSessionKey();

  /**
   * <pre>
   * Remote attestation data which will be present in the initial license
   * request for ChromeOS client devices operating in verified mode. Remote
   * attestation challenge data is |msg| field above. Optional.
   * </pre>
   *
   * <code>optional bytes remote_attestation = 5;</code>
   * @return Whether the remoteAttestation field is set.
   */
  boolean hasRemoteAttestation();
  /**
   * <pre>
   * Remote attestation data which will be present in the initial license
   * request for ChromeOS client devices operating in verified mode. Remote
   * attestation challenge data is |msg| field above. Optional.
   * </pre>
   *
   * <code>optional bytes remote_attestation = 5;</code>
   * @return The remoteAttestation.
   */
  com.google.protobuf.ByteString getRemoteAttestation();

  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData> 
      getMetricDataList();
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.MetricData getMetricData(int index);
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  int getMetricDataCount();
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder> 
      getMetricDataOrBuilderList();
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder getMetricDataOrBuilder(
      int index);

  /**
   * <pre>
   * Version information from the SDK and license service. This information is
   * provided in the license response.
   * </pre>
   *
   * <code>optional .VersionInfo service_version_info = 7;</code>
   * @return Whether the serviceVersionInfo field is set.
   */
  boolean hasServiceVersionInfo();
  /**
   * <pre>
   * Version information from the SDK and license service. This information is
   * provided in the license response.
   * </pre>
   *
   * <code>optional .VersionInfo service_version_info = 7;</code>
   * @return The serviceVersionInfo.
   */
  de.klassenserver7b.widevine4j.protobuf.VersionInfo getServiceVersionInfo();
  /**
   * <pre>
   * Version information from the SDK and license service. This information is
   * provided in the license response.
   * </pre>
   *
   * <code>optional .VersionInfo service_version_info = 7;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.VersionInfoOrBuilder getServiceVersionInfoOrBuilder();

  /**
   * <pre>
   * Optional field that contains the algorithm type used to generate the
   * session_key and signature in a LICENSE message.
   * </pre>
   *
   * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
   * @return Whether the sessionKeyType field is set.
   */
  boolean hasSessionKeyType();
  /**
   * <pre>
   * Optional field that contains the algorithm type used to generate the
   * session_key and signature in a LICENSE message.
   * </pre>
   *
   * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
   * @return The sessionKeyType.
   */
  de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType getSessionKeyType();

  /**
   * <pre>
   * The core message is the simple serialization of fields used by OEMCrypto.
   * This field was introduced in OEMCrypto API v16.
   * </pre>
   *
   * <code>optional bytes oemcrypto_core_message = 9;</code>
   * @return Whether the oemcryptoCoreMessage field is set.
   */
  boolean hasOemcryptoCoreMessage();
  /**
   * <pre>
   * The core message is the simple serialization of fields used by OEMCrypto.
   * This field was introduced in OEMCrypto API v16.
   * </pre>
   *
   * <code>optional bytes oemcrypto_core_message = 9;</code>
   * @return The oemcryptoCoreMessage.
   */
  com.google.protobuf.ByteString getOemcryptoCoreMessage();
}
