// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface SignedDrmCertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SignedDrmCertificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Serialized certificate. Required.
   * </pre>
   *
   * <code>optional bytes drm_certificate = 1;</code>
   * @return Whether the drmCertificate field is set.
   */
  boolean hasDrmCertificate();
  /**
   * <pre>
   * Serialized certificate. Required.
   * </pre>
   *
   * <code>optional bytes drm_certificate = 1;</code>
   * @return The drmCertificate.
   */
  com.google.protobuf.ByteString getDrmCertificate();

  /**
   * <pre>
   * Signature of certificate. Signed with root or intermediate
   * certificate specified below. Required.
   * </pre>
   *
   * <code>optional bytes signature = 2;</code>
   * @return Whether the signature field is set.
   */
  boolean hasSignature();
  /**
   * <pre>
   * Signature of certificate. Signed with root or intermediate
   * certificate specified below. Required.
   * </pre>
   *
   * <code>optional bytes signature = 2;</code>
   * @return The signature.
   */
  com.google.protobuf.ByteString getSignature();

  /**
   * <pre>
   * SignedDrmCertificate used to sign this certificate.
   * </pre>
   *
   * <code>optional .SignedDrmCertificate signer = 3;</code>
   * @return Whether the signer field is set.
   */
  boolean hasSigner();
  /**
   * <pre>
   * SignedDrmCertificate used to sign this certificate.
   * </pre>
   *
   * <code>optional .SignedDrmCertificate signer = 3;</code>
   * @return The signer.
   */
  de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate getSigner();
  /**
   * <pre>
   * SignedDrmCertificate used to sign this certificate.
   * </pre>
   *
   * <code>optional .SignedDrmCertificate signer = 3;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificateOrBuilder getSignerOrBuilder();

  /**
   * <pre>
   * Optional field that indicates the hash algorithm used in signature scheme.
   * </pre>
   *
   * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
   * @return Whether the hashAlgorithm field is set.
   */
  boolean hasHashAlgorithm();
  /**
   * <pre>
   * Optional field that indicates the hash algorithm used in signature scheme.
   * </pre>
   *
   * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
   * @return The hashAlgorithm.
   */
  de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto getHashAlgorithm();
}
