// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * Protobuf type {@code SignedMessage}
 */
public final class SignedMessage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SignedMessage)
    SignedMessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SignedMessage.newBuilder() to construct.
  private SignedMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignedMessage() {
    type_ = 1;
    msg_ = com.google.protobuf.ByteString.EMPTY;
    signature_ = com.google.protobuf.ByteString.EMPTY;
    sessionKey_ = com.google.protobuf.ByteString.EMPTY;
    remoteAttestation_ = com.google.protobuf.ByteString.EMPTY;
    metricData_ = java.util.Collections.emptyList();
    sessionKeyType_ = 1;
    oemcryptoCoreMessage_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SignedMessage();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedMessage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedMessage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.klassenserver7b.widevine4j.protobuf.SignedMessage.class, de.klassenserver7b.widevine4j.protobuf.SignedMessage.Builder.class);
  }

  /**
   * Protobuf enum {@code SignedMessage.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LICENSE_REQUEST = 1;</code>
     */
    LICENSE_REQUEST(1),
    /**
     * <code>LICENSE = 2;</code>
     */
    LICENSE(2),
    /**
     * <code>ERROR_RESPONSE = 3;</code>
     */
    ERROR_RESPONSE(3),
    /**
     * <code>SERVICE_CERTIFICATE_REQUEST = 4;</code>
     */
    SERVICE_CERTIFICATE_REQUEST(4),
    /**
     * <code>SERVICE_CERTIFICATE = 5;</code>
     */
    SERVICE_CERTIFICATE(5),
    /**
     * <code>SUB_LICENSE = 6;</code>
     */
    SUB_LICENSE(6),
    /**
     * <code>CAS_LICENSE_REQUEST = 7;</code>
     */
    CAS_LICENSE_REQUEST(7),
    /**
     * <code>CAS_LICENSE = 8;</code>
     */
    CAS_LICENSE(8),
    /**
     * <code>EXTERNAL_LICENSE_REQUEST = 9;</code>
     */
    EXTERNAL_LICENSE_REQUEST(9),
    /**
     * <code>EXTERNAL_LICENSE = 10;</code>
     */
    EXTERNAL_LICENSE(10),
    ;

    /**
     * <code>LICENSE_REQUEST = 1;</code>
     */
    public static final int LICENSE_REQUEST_VALUE = 1;
    /**
     * <code>LICENSE = 2;</code>
     */
    public static final int LICENSE_VALUE = 2;
    /**
     * <code>ERROR_RESPONSE = 3;</code>
     */
    public static final int ERROR_RESPONSE_VALUE = 3;
    /**
     * <code>SERVICE_CERTIFICATE_REQUEST = 4;</code>
     */
    public static final int SERVICE_CERTIFICATE_REQUEST_VALUE = 4;
    /**
     * <code>SERVICE_CERTIFICATE = 5;</code>
     */
    public static final int SERVICE_CERTIFICATE_VALUE = 5;
    /**
     * <code>SUB_LICENSE = 6;</code>
     */
    public static final int SUB_LICENSE_VALUE = 6;
    /**
     * <code>CAS_LICENSE_REQUEST = 7;</code>
     */
    public static final int CAS_LICENSE_REQUEST_VALUE = 7;
    /**
     * <code>CAS_LICENSE = 8;</code>
     */
    public static final int CAS_LICENSE_VALUE = 8;
    /**
     * <code>EXTERNAL_LICENSE_REQUEST = 9;</code>
     */
    public static final int EXTERNAL_LICENSE_REQUEST_VALUE = 9;
    /**
     * <code>EXTERNAL_LICENSE = 10;</code>
     */
    public static final int EXTERNAL_LICENSE_VALUE = 10;


    @Override
	public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 1: return LICENSE_REQUEST;
        case 2: return LICENSE;
        case 3: return ERROR_RESPONSE;
        case 4: return SERVICE_CERTIFICATE_REQUEST;
        case 5: return SERVICE_CERTIFICATE;
        case 6: return SUB_LICENSE;
        case 7: return CAS_LICENSE_REQUEST;
        case 8: return CAS_LICENSE;
        case 9: return EXTERNAL_LICENSE_REQUEST;
        case 10: return EXTERNAL_LICENSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            @Override
			public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    @Override
	public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    @Override
	public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.SignedMessage.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SignedMessage.MessageType)
  }

  /**
   * Protobuf enum {@code SignedMessage.SessionKeyType}
   */
  public enum SessionKeyType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNDEFINED = 0;</code>
     */
    UNDEFINED(0),
    /**
     * <code>WRAPPED_AES_KEY = 1;</code>
     */
    WRAPPED_AES_KEY(1),
    /**
     * <code>EPHERMERAL_ECC_PUBLIC_KEY = 2;</code>
     */
    EPHERMERAL_ECC_PUBLIC_KEY(2),
    ;

    /**
     * <code>UNDEFINED = 0;</code>
     */
    public static final int UNDEFINED_VALUE = 0;
    /**
     * <code>WRAPPED_AES_KEY = 1;</code>
     */
    public static final int WRAPPED_AES_KEY_VALUE = 1;
    /**
     * <code>EPHERMERAL_ECC_PUBLIC_KEY = 2;</code>
     */
    public static final int EPHERMERAL_ECC_PUBLIC_KEY_VALUE = 2;


    @Override
	public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static SessionKeyType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static SessionKeyType forNumber(int value) {
      switch (value) {
        case 0: return UNDEFINED;
        case 1: return WRAPPED_AES_KEY;
        case 2: return EPHERMERAL_ECC_PUBLIC_KEY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SessionKeyType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        SessionKeyType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SessionKeyType>() {
            @Override
			public SessionKeyType findValueByNumber(int number) {
              return SessionKeyType.forNumber(number);
            }
          };

    @Override
	public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    @Override
	public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.SignedMessage.getDescriptor().getEnumTypes().get(1);
    }

    private static final SessionKeyType[] VALUES = values();

    public static SessionKeyType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private SessionKeyType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SignedMessage.SessionKeyType)
  }

  private int bitField0_;
  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_ = 1;
  /**
   * <code>optional .SignedMessage.MessageType type = 1;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override public boolean hasType() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>optional .SignedMessage.MessageType type = 1;</code>
   * @return The type.
   */
  @java.lang.Override public de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType getType() {
    de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType result = de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType.forNumber(type_);
    return result == null ? de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType.LICENSE_REQUEST : result;
  }

  public static final int MSG_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <code>optional bytes msg = 2;</code>
   * @return Whether the msg field is set.
   */
  @java.lang.Override
  public boolean hasMsg() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>optional bytes msg = 2;</code>
   * @return The msg.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getMsg() {
    return msg_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 3;
  private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Required field that contains the signature of the bytes of msg.
   * For license requests, the signing algorithm is determined by the
   * certificate contained in the request.
   * For license responses, the signing algorithm is HMAC with signing key based
   * on |session_key|.
   * </pre>
   *
   * <code>optional bytes signature = 3;</code>
   * @return Whether the signature field is set.
   */
  @java.lang.Override
  public boolean hasSignature() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * Required field that contains the signature of the bytes of msg.
   * For license requests, the signing algorithm is determined by the
   * certificate contained in the request.
   * For license responses, the signing algorithm is HMAC with signing key based
   * on |session_key|.
   * </pre>
   *
   * <code>optional bytes signature = 3;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  public static final int SESSION_KEY_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString sessionKey_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * If populated, the contents of this field will be signaled by the
   * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
   * key is the bytes of an encrypted AES key. If the |session_key_type| is
   * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
   * serialized ECC public key.
   * </pre>
   *
   * <code>optional bytes session_key = 4;</code>
   * @return Whether the sessionKey field is set.
   */
  @java.lang.Override
  public boolean hasSessionKey() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * If populated, the contents of this field will be signaled by the
   * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
   * key is the bytes of an encrypted AES key. If the |session_key_type| is
   * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
   * serialized ECC public key.
   * </pre>
   *
   * <code>optional bytes session_key = 4;</code>
   * @return The sessionKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSessionKey() {
    return sessionKey_;
  }

  public static final int REMOTE_ATTESTATION_FIELD_NUMBER = 5;
  private com.google.protobuf.ByteString remoteAttestation_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Remote attestation data which will be present in the initial license
   * request for ChromeOS client devices operating in verified mode. Remote
   * attestation challenge data is |msg| field above. Optional.
   * </pre>
   *
   * <code>optional bytes remote_attestation = 5;</code>
   * @return Whether the remoteAttestation field is set.
   */
  @java.lang.Override
  public boolean hasRemoteAttestation() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <pre>
   * Remote attestation data which will be present in the initial license
   * request for ChromeOS client devices operating in verified mode. Remote
   * attestation challenge data is |msg| field above. Optional.
   * </pre>
   *
   * <code>optional bytes remote_attestation = 5;</code>
   * @return The remoteAttestation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getRemoteAttestation() {
    return remoteAttestation_;
  }

  public static final int METRIC_DATA_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData> metricData_;
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData> getMetricDataList() {
    return metricData_;
  }
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  @java.lang.Override
  public java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder> 
      getMetricDataOrBuilderList() {
    return metricData_;
  }
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  @java.lang.Override
  public int getMetricDataCount() {
    return metricData_.size();
  }
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.MetricData getMetricData(int index) {
    return metricData_.get(index);
  }
  /**
   * <code>repeated .MetricData metric_data = 6;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder getMetricDataOrBuilder(
      int index) {
    return metricData_.get(index);
  }

  public static final int SERVICE_VERSION_INFO_FIELD_NUMBER = 7;
  private de.klassenserver7b.widevine4j.protobuf.VersionInfo serviceVersionInfo_;
  /**
   * <pre>
   * Version information from the SDK and license service. This information is
   * provided in the license response.
   * </pre>
   *
   * <code>optional .VersionInfo service_version_info = 7;</code>
   * @return Whether the serviceVersionInfo field is set.
   */
  @java.lang.Override
  public boolean hasServiceVersionInfo() {
    return ((bitField0_ & 0x00000020) != 0);
  }
  /**
   * <pre>
   * Version information from the SDK and license service. This information is
   * provided in the license response.
   * </pre>
   *
   * <code>optional .VersionInfo service_version_info = 7;</code>
   * @return The serviceVersionInfo.
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.VersionInfo getServiceVersionInfo() {
    return serviceVersionInfo_ == null ? de.klassenserver7b.widevine4j.protobuf.VersionInfo.getDefaultInstance() : serviceVersionInfo_;
  }
  /**
   * <pre>
   * Version information from the SDK and license service. This information is
   * provided in the license response.
   * </pre>
   *
   * <code>optional .VersionInfo service_version_info = 7;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.VersionInfoOrBuilder getServiceVersionInfoOrBuilder() {
    return serviceVersionInfo_ == null ? de.klassenserver7b.widevine4j.protobuf.VersionInfo.getDefaultInstance() : serviceVersionInfo_;
  }

  public static final int SESSION_KEY_TYPE_FIELD_NUMBER = 8;
  private int sessionKeyType_ = 1;
  /**
   * <pre>
   * Optional field that contains the algorithm type used to generate the
   * session_key and signature in a LICENSE message.
   * </pre>
   *
   * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
   * @return Whether the sessionKeyType field is set.
   */
  @java.lang.Override public boolean hasSessionKeyType() {
    return ((bitField0_ & 0x00000040) != 0);
  }
  /**
   * <pre>
   * Optional field that contains the algorithm type used to generate the
   * session_key and signature in a LICENSE message.
   * </pre>
   *
   * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
   * @return The sessionKeyType.
   */
  @java.lang.Override public de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType getSessionKeyType() {
    de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType result = de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType.forNumber(sessionKeyType_);
    return result == null ? de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType.WRAPPED_AES_KEY : result;
  }

  public static final int OEMCRYPTO_CORE_MESSAGE_FIELD_NUMBER = 9;
  private com.google.protobuf.ByteString oemcryptoCoreMessage_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * The core message is the simple serialization of fields used by OEMCrypto.
   * This field was introduced in OEMCrypto API v16.
   * </pre>
   *
   * <code>optional bytes oemcrypto_core_message = 9;</code>
   * @return Whether the oemcryptoCoreMessage field is set.
   */
  @java.lang.Override
  public boolean hasOemcryptoCoreMessage() {
    return ((bitField0_ & 0x00000080) != 0);
  }
  /**
   * <pre>
   * The core message is the simple serialization of fields used by OEMCrypto.
   * This field was introduced in OEMCrypto API v16.
   * </pre>
   *
   * <code>optional bytes oemcrypto_core_message = 9;</code>
   * @return The oemcryptoCoreMessage.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getOemcryptoCoreMessage() {
    return oemcryptoCoreMessage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeEnum(1, type_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, msg_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeBytes(3, signature_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeBytes(4, sessionKey_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeBytes(5, remoteAttestation_);
    }
    for (int i = 0; i < metricData_.size(); i++) {
      output.writeMessage(6, metricData_.get(i));
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      output.writeMessage(7, getServiceVersionInfo());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      output.writeEnum(8, sessionKeyType_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      output.writeBytes(9, oemcryptoCoreMessage_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, msg_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(3, signature_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, sessionKey_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(5, remoteAttestation_);
    }
    for (int i = 0; i < metricData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, metricData_.get(i));
    }
    if (((bitField0_ & 0x00000020) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getServiceVersionInfo());
    }
    if (((bitField0_ & 0x00000040) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(8, sessionKeyType_);
    }
    if (((bitField0_ & 0x00000080) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(9, oemcryptoCoreMessage_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.SignedMessage)) {
      return super.equals(obj);
    }
    de.klassenserver7b.widevine4j.protobuf.SignedMessage other = (de.klassenserver7b.widevine4j.protobuf.SignedMessage) obj;

    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (type_ != other.type_) return false;
    }
    if (hasMsg() != other.hasMsg()) return false;
    if (hasMsg()) {
      if (!getMsg()
          .equals(other.getMsg())) return false;
    }
    if (hasSignature() != other.hasSignature()) return false;
    if (hasSignature()) {
      if (!getSignature()
          .equals(other.getSignature())) return false;
    }
    if (hasSessionKey() != other.hasSessionKey()) return false;
    if (hasSessionKey()) {
      if (!getSessionKey()
          .equals(other.getSessionKey())) return false;
    }
    if (hasRemoteAttestation() != other.hasRemoteAttestation()) return false;
    if (hasRemoteAttestation()) {
      if (!getRemoteAttestation()
          .equals(other.getRemoteAttestation())) return false;
    }
    if (!getMetricDataList()
        .equals(other.getMetricDataList())) return false;
    if (hasServiceVersionInfo() != other.hasServiceVersionInfo()) return false;
    if (hasServiceVersionInfo()) {
      if (!getServiceVersionInfo()
          .equals(other.getServiceVersionInfo())) return false;
    }
    if (hasSessionKeyType() != other.hasSessionKeyType()) return false;
    if (hasSessionKeyType()) {
      if (sessionKeyType_ != other.sessionKeyType_) return false;
    }
    if (hasOemcryptoCoreMessage() != other.hasOemcryptoCoreMessage()) return false;
    if (hasOemcryptoCoreMessage()) {
      if (!getOemcryptoCoreMessage()
          .equals(other.getOemcryptoCoreMessage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
    }
    if (hasMsg()) {
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
    }
    if (hasSignature()) {
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
    }
    if (hasSessionKey()) {
      hash = (37 * hash) + SESSION_KEY_FIELD_NUMBER;
      hash = (53 * hash) + getSessionKey().hashCode();
    }
    if (hasRemoteAttestation()) {
      hash = (37 * hash) + REMOTE_ATTESTATION_FIELD_NUMBER;
      hash = (53 * hash) + getRemoteAttestation().hashCode();
    }
    if (getMetricDataCount() > 0) {
      hash = (37 * hash) + METRIC_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getMetricDataList().hashCode();
    }
    if (hasServiceVersionInfo()) {
      hash = (37 * hash) + SERVICE_VERSION_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getServiceVersionInfo().hashCode();
    }
    if (hasSessionKeyType()) {
      hash = (37 * hash) + SESSION_KEY_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + sessionKeyType_;
    }
    if (hasOemcryptoCoreMessage()) {
      hash = (37 * hash) + OEMCRYPTO_CORE_MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getOemcryptoCoreMessage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.SignedMessage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code SignedMessage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SignedMessage)
      de.klassenserver7b.widevine4j.protobuf.SignedMessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.SignedMessage.class, de.klassenserver7b.widevine4j.protobuf.SignedMessage.Builder.class);
    }

    // Construct using de.klassenserver7b.widevine4j.protobuf.SignedMessage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getMetricDataFieldBuilder();
        getServiceVersionInfoFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      type_ = 1;
      msg_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      sessionKey_ = com.google.protobuf.ByteString.EMPTY;
      remoteAttestation_ = com.google.protobuf.ByteString.EMPTY;
      if (metricDataBuilder_ == null) {
        metricData_ = java.util.Collections.emptyList();
      } else {
        metricData_ = null;
        metricDataBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000020);
      serviceVersionInfo_ = null;
      if (serviceVersionInfoBuilder_ != null) {
        serviceVersionInfoBuilder_.dispose();
        serviceVersionInfoBuilder_ = null;
      }
      sessionKeyType_ = 1;
      oemcryptoCoreMessage_ = com.google.protobuf.ByteString.EMPTY;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedMessage_descriptor;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedMessage getDefaultInstanceForType() {
      return de.klassenserver7b.widevine4j.protobuf.SignedMessage.getDefaultInstance();
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedMessage build() {
      de.klassenserver7b.widevine4j.protobuf.SignedMessage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedMessage buildPartial() {
      de.klassenserver7b.widevine4j.protobuf.SignedMessage result = new de.klassenserver7b.widevine4j.protobuf.SignedMessage(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(de.klassenserver7b.widevine4j.protobuf.SignedMessage result) {
      if (metricDataBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0)) {
          metricData_ = java.util.Collections.unmodifiableList(metricData_);
          bitField0_ = (bitField0_ & ~0x00000020);
        }
        result.metricData_ = metricData_;
      } else {
        result.metricData_ = metricDataBuilder_.build();
      }
    }

    private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.SignedMessage result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.type_ = type_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.msg_ = msg_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.signature_ = signature_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.sessionKey_ = sessionKey_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.remoteAttestation_ = remoteAttestation_;
        to_bitField0_ |= 0x00000010;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.serviceVersionInfo_ = serviceVersionInfoBuilder_ == null
            ? serviceVersionInfo_
            : serviceVersionInfoBuilder_.build();
        to_bitField0_ |= 0x00000020;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.sessionKeyType_ = sessionKeyType_;
        to_bitField0_ |= 0x00000040;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.oemcryptoCoreMessage_ = oemcryptoCoreMessage_;
        to_bitField0_ |= 0x00000080;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.klassenserver7b.widevine4j.protobuf.SignedMessage) {
        return mergeFrom((de.klassenserver7b.widevine4j.protobuf.SignedMessage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.SignedMessage other) {
      if (other == de.klassenserver7b.widevine4j.protobuf.SignedMessage.getDefaultInstance()) return this;
      if (other.hasType()) {
        setType(other.getType());
      }
      if (other.hasMsg()) {
        setMsg(other.getMsg());
      }
      if (other.hasSignature()) {
        setSignature(other.getSignature());
      }
      if (other.hasSessionKey()) {
        setSessionKey(other.getSessionKey());
      }
      if (other.hasRemoteAttestation()) {
        setRemoteAttestation(other.getRemoteAttestation());
      }
      if (metricDataBuilder_ == null) {
        if (!other.metricData_.isEmpty()) {
          if (metricData_.isEmpty()) {
            metricData_ = other.metricData_;
            bitField0_ = (bitField0_ & ~0x00000020);
          } else {
            ensureMetricDataIsMutable();
            metricData_.addAll(other.metricData_);
          }
          onChanged();
        }
      } else {
        if (!other.metricData_.isEmpty()) {
          if (metricDataBuilder_.isEmpty()) {
            metricDataBuilder_.dispose();
            metricDataBuilder_ = null;
            metricData_ = other.metricData_;
            bitField0_ = (bitField0_ & ~0x00000020);
            metricDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getMetricDataFieldBuilder() : null;
          } else {
            metricDataBuilder_.addAllMessages(other.metricData_);
          }
        }
      }
      if (other.hasServiceVersionInfo()) {
        mergeServiceVersionInfo(other.getServiceVersionInfo());
      }
      if (other.hasSessionKeyType()) {
        setSessionKeyType(other.getSessionKeyType());
      }
      if (other.hasOemcryptoCoreMessage()) {
        setOemcryptoCoreMessage(other.getOemcryptoCoreMessage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int tmpRaw = input.readEnum();
              de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType tmpValue =
                  de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(1, tmpRaw);
              } else {
                type_ = tmpRaw;
                bitField0_ |= 0x00000001;
              }
              break;
            } // case 8
            case 18: {
              msg_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              signature_ = input.readBytes();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              sessionKey_ = input.readBytes();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              remoteAttestation_ = input.readBytes();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            case 50: {
              @SuppressWarnings("deprecation")
			de.klassenserver7b.widevine4j.protobuf.MetricData m =
                  input.readMessage(
                      de.klassenserver7b.widevine4j.protobuf.MetricData.PARSER,
                      extensionRegistry);
              if (metricDataBuilder_ == null) {
                ensureMetricDataIsMutable();
                metricData_.add(m);
              } else {
                metricDataBuilder_.addMessage(m);
              }
              break;
            } // case 50
            case 58: {
              input.readMessage(
                  getServiceVersionInfoFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000040;
              break;
            } // case 58
            case 64: {
              int tmpRaw = input.readEnum();
              de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType tmpValue =
                  de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(8, tmpRaw);
              } else {
                sessionKeyType_ = tmpRaw;
                bitField0_ |= 0x00000080;
              }
              break;
            } // case 64
            case 74: {
              oemcryptoCoreMessage_ = input.readBytes();
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int type_ = 1;
    /**
     * <code>optional .SignedMessage.MessageType type = 1;</code>
     * @return Whether the type field is set.
     */
    @java.lang.Override public boolean hasType() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional .SignedMessage.MessageType type = 1;</code>
     * @return The type.
     */
    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType getType() {
      de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType result = de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType.forNumber(type_);
      return result == null ? de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType.LICENSE_REQUEST : result;
    }
    /**
     * <code>optional .SignedMessage.MessageType type = 1;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(de.klassenserver7b.widevine4j.protobuf.SignedMessage.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000001;
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .SignedMessage.MessageType type = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      bitField0_ = (bitField0_ & ~0x00000001);
      type_ = 1;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>optional bytes msg = 2;</code>
     * @return Whether the msg field is set.
     */
    @java.lang.Override
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional bytes msg = 2;</code>
     * @return The msg.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }
    /**
     * <code>optional bytes msg = 2;</code>
     * @param value The msg to set.
     * @return This builder for chaining.
     */
    public Builder setMsg(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      msg_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>optional bytes msg = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsg() {
      bitField0_ = (bitField0_ & ~0x00000002);
      msg_ = getDefaultInstance().getMsg();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Required field that contains the signature of the bytes of msg.
     * For license requests, the signing algorithm is determined by the
     * certificate contained in the request.
     * For license responses, the signing algorithm is HMAC with signing key based
     * on |session_key|.
     * </pre>
     *
     * <code>optional bytes signature = 3;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * Required field that contains the signature of the bytes of msg.
     * For license requests, the signing algorithm is determined by the
     * certificate contained in the request.
     * For license responses, the signing algorithm is HMAC with signing key based
     * on |session_key|.
     * </pre>
     *
     * <code>optional bytes signature = 3;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * Required field that contains the signature of the bytes of msg.
     * For license requests, the signing algorithm is determined by the
     * certificate contained in the request.
     * For license responses, the signing algorithm is HMAC with signing key based
     * on |session_key|.
     * </pre>
     *
     * <code>optional bytes signature = 3;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      signature_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Required field that contains the signature of the bytes of msg.
     * For license requests, the signing algorithm is determined by the
     * certificate contained in the request.
     * For license responses, the signing algorithm is HMAC with signing key based
     * on |session_key|.
     * </pre>
     *
     * <code>optional bytes signature = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000004);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString sessionKey_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * If populated, the contents of this field will be signaled by the
     * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
     * key is the bytes of an encrypted AES key. If the |session_key_type| is
     * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
     * serialized ECC public key.
     * </pre>
     *
     * <code>optional bytes session_key = 4;</code>
     * @return Whether the sessionKey field is set.
     */
    @java.lang.Override
    public boolean hasSessionKey() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * If populated, the contents of this field will be signaled by the
     * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
     * key is the bytes of an encrypted AES key. If the |session_key_type| is
     * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
     * serialized ECC public key.
     * </pre>
     *
     * <code>optional bytes session_key = 4;</code>
     * @return The sessionKey.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSessionKey() {
      return sessionKey_;
    }
    /**
     * <pre>
     * If populated, the contents of this field will be signaled by the
     * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
     * key is the bytes of an encrypted AES key. If the |session_key_type| is
     * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
     * serialized ECC public key.
     * </pre>
     *
     * <code>optional bytes session_key = 4;</code>
     * @param value The sessionKey to set.
     * @return This builder for chaining.
     */
    public Builder setSessionKey(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      sessionKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * If populated, the contents of this field will be signaled by the
     * |session_key_type| type. If the |session_key_type| is WRAPPED_AES_KEY the
     * key is the bytes of an encrypted AES key. If the |session_key_type| is
     * EPHERMERAL_ECC_PUBLIC_KEY the field contains the bytes of an RFC5208 ASN1
     * serialized ECC public key.
     * </pre>
     *
     * <code>optional bytes session_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionKey() {
      bitField0_ = (bitField0_ & ~0x00000008);
      sessionKey_ = getDefaultInstance().getSessionKey();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString remoteAttestation_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Remote attestation data which will be present in the initial license
     * request for ChromeOS client devices operating in verified mode. Remote
     * attestation challenge data is |msg| field above. Optional.
     * </pre>
     *
     * <code>optional bytes remote_attestation = 5;</code>
     * @return Whether the remoteAttestation field is set.
     */
    @java.lang.Override
    public boolean hasRemoteAttestation() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <pre>
     * Remote attestation data which will be present in the initial license
     * request for ChromeOS client devices operating in verified mode. Remote
     * attestation challenge data is |msg| field above. Optional.
     * </pre>
     *
     * <code>optional bytes remote_attestation = 5;</code>
     * @return The remoteAttestation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getRemoteAttestation() {
      return remoteAttestation_;
    }
    /**
     * <pre>
     * Remote attestation data which will be present in the initial license
     * request for ChromeOS client devices operating in verified mode. Remote
     * attestation challenge data is |msg| field above. Optional.
     * </pre>
     *
     * <code>optional bytes remote_attestation = 5;</code>
     * @param value The remoteAttestation to set.
     * @return This builder for chaining.
     */
    public Builder setRemoteAttestation(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      remoteAttestation_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Remote attestation data which will be present in the initial license
     * request for ChromeOS client devices operating in verified mode. Remote
     * attestation challenge data is |msg| field above. Optional.
     * </pre>
     *
     * <code>optional bytes remote_attestation = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearRemoteAttestation() {
      bitField0_ = (bitField0_ & ~0x00000010);
      remoteAttestation_ = getDefaultInstance().getRemoteAttestation();
      onChanged();
      return this;
    }

    private java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData> metricData_ =
      java.util.Collections.emptyList();
    private void ensureMetricDataIsMutable() {
      if (!((bitField0_ & 0x00000020) != 0)) {
        metricData_ = new java.util.ArrayList<de.klassenserver7b.widevine4j.protobuf.MetricData>(metricData_);
        bitField0_ |= 0x00000020;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.MetricData, de.klassenserver7b.widevine4j.protobuf.MetricData.Builder, de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder> metricDataBuilder_;

    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    @Override
	public java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData> getMetricDataList() {
      if (metricDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(metricData_);
      } else {
        return metricDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    @Override
	public int getMetricDataCount() {
      if (metricDataBuilder_ == null) {
        return metricData_.size();
      } else {
        return metricDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    @Override
	public de.klassenserver7b.widevine4j.protobuf.MetricData getMetricData(int index) {
      if (metricDataBuilder_ == null) {
        return metricData_.get(index);
      } else {
        return metricDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder setMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData value) {
      if (metricDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricDataIsMutable();
        metricData_.set(index, value);
        onChanged();
      } else {
        metricDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder setMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData.Builder builderForValue) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.set(index, builderForValue.build());
        onChanged();
      } else {
        metricDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder addMetricData(de.klassenserver7b.widevine4j.protobuf.MetricData value) {
      if (metricDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricDataIsMutable();
        metricData_.add(value);
        onChanged();
      } else {
        metricDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder addMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData value) {
      if (metricDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureMetricDataIsMutable();
        metricData_.add(index, value);
        onChanged();
      } else {
        metricDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder addMetricData(
        de.klassenserver7b.widevine4j.protobuf.MetricData.Builder builderForValue) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.add(builderForValue.build());
        onChanged();
      } else {
        metricDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder addMetricData(
        int index, de.klassenserver7b.widevine4j.protobuf.MetricData.Builder builderForValue) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.add(index, builderForValue.build());
        onChanged();
      } else {
        metricDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder addAllMetricData(
        java.lang.Iterable<? extends de.klassenserver7b.widevine4j.protobuf.MetricData> values) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, metricData_);
        onChanged();
      } else {
        metricDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder clearMetricData() {
      if (metricDataBuilder_ == null) {
        metricData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
      } else {
        metricDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public Builder removeMetricData(int index) {
      if (metricDataBuilder_ == null) {
        ensureMetricDataIsMutable();
        metricData_.remove(index);
        onChanged();
      } else {
        metricDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.Builder getMetricDataBuilder(
        int index) {
      return getMetricDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    @Override
	public de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder getMetricDataOrBuilder(
        int index) {
      if (metricDataBuilder_ == null) {
        return metricData_.get(index);  } else {
        return metricDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    @Override
	public java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder> 
         getMetricDataOrBuilderList() {
      if (metricDataBuilder_ != null) {
        return metricDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(metricData_);
      }
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.Builder addMetricDataBuilder() {
      return getMetricDataFieldBuilder().addBuilder(
          de.klassenserver7b.widevine4j.protobuf.MetricData.getDefaultInstance());
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.MetricData.Builder addMetricDataBuilder(
        int index) {
      return getMetricDataFieldBuilder().addBuilder(
          index, de.klassenserver7b.widevine4j.protobuf.MetricData.getDefaultInstance());
    }
    /**
     * <code>repeated .MetricData metric_data = 6;</code>
     */
    public java.util.List<de.klassenserver7b.widevine4j.protobuf.MetricData.Builder> 
         getMetricDataBuilderList() {
      return getMetricDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.MetricData, de.klassenserver7b.widevine4j.protobuf.MetricData.Builder, de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder> 
        getMetricDataFieldBuilder() {
      if (metricDataBuilder_ == null) {
        metricDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            de.klassenserver7b.widevine4j.protobuf.MetricData, de.klassenserver7b.widevine4j.protobuf.MetricData.Builder, de.klassenserver7b.widevine4j.protobuf.MetricDataOrBuilder>(
                metricData_,
                ((bitField0_ & 0x00000020) != 0),
                getParentForChildren(),
                isClean());
        metricData_ = null;
      }
      return metricDataBuilder_;
    }

    private de.klassenserver7b.widevine4j.protobuf.VersionInfo serviceVersionInfo_;
    private com.google.protobuf.SingleFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.VersionInfo, de.klassenserver7b.widevine4j.protobuf.VersionInfo.Builder, de.klassenserver7b.widevine4j.protobuf.VersionInfoOrBuilder> serviceVersionInfoBuilder_;
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     * @return Whether the serviceVersionInfo field is set.
     */
    @Override
	public boolean hasServiceVersionInfo() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     * @return The serviceVersionInfo.
     */
    @Override
	public de.klassenserver7b.widevine4j.protobuf.VersionInfo getServiceVersionInfo() {
      if (serviceVersionInfoBuilder_ == null) {
        return serviceVersionInfo_ == null ? de.klassenserver7b.widevine4j.protobuf.VersionInfo.getDefaultInstance() : serviceVersionInfo_;
      } else {
        return serviceVersionInfoBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     */
    public Builder setServiceVersionInfo(de.klassenserver7b.widevine4j.protobuf.VersionInfo value) {
      if (serviceVersionInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        serviceVersionInfo_ = value;
      } else {
        serviceVersionInfoBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     */
    public Builder setServiceVersionInfo(
        de.klassenserver7b.widevine4j.protobuf.VersionInfo.Builder builderForValue) {
      if (serviceVersionInfoBuilder_ == null) {
        serviceVersionInfo_ = builderForValue.build();
      } else {
        serviceVersionInfoBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     */
    public Builder mergeServiceVersionInfo(de.klassenserver7b.widevine4j.protobuf.VersionInfo value) {
      if (serviceVersionInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000040) != 0) &&
          serviceVersionInfo_ != null &&
          serviceVersionInfo_ != de.klassenserver7b.widevine4j.protobuf.VersionInfo.getDefaultInstance()) {
          getServiceVersionInfoBuilder().mergeFrom(value);
        } else {
          serviceVersionInfo_ = value;
        }
      } else {
        serviceVersionInfoBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     */
    public Builder clearServiceVersionInfo() {
      bitField0_ = (bitField0_ & ~0x00000040);
      serviceVersionInfo_ = null;
      if (serviceVersionInfoBuilder_ != null) {
        serviceVersionInfoBuilder_.dispose();
        serviceVersionInfoBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.VersionInfo.Builder getServiceVersionInfoBuilder() {
      bitField0_ |= 0x00000040;
      onChanged();
      return getServiceVersionInfoFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     */
    @Override
	public de.klassenserver7b.widevine4j.protobuf.VersionInfoOrBuilder getServiceVersionInfoOrBuilder() {
      if (serviceVersionInfoBuilder_ != null) {
        return serviceVersionInfoBuilder_.getMessageOrBuilder();
      } else {
        return serviceVersionInfo_ == null ?
            de.klassenserver7b.widevine4j.protobuf.VersionInfo.getDefaultInstance() : serviceVersionInfo_;
      }
    }
    /**
     * <pre>
     * Version information from the SDK and license service. This information is
     * provided in the license response.
     * </pre>
     *
     * <code>optional .VersionInfo service_version_info = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.VersionInfo, de.klassenserver7b.widevine4j.protobuf.VersionInfo.Builder, de.klassenserver7b.widevine4j.protobuf.VersionInfoOrBuilder> 
        getServiceVersionInfoFieldBuilder() {
      if (serviceVersionInfoBuilder_ == null) {
        serviceVersionInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            de.klassenserver7b.widevine4j.protobuf.VersionInfo, de.klassenserver7b.widevine4j.protobuf.VersionInfo.Builder, de.klassenserver7b.widevine4j.protobuf.VersionInfoOrBuilder>(
                getServiceVersionInfo(),
                getParentForChildren(),
                isClean());
        serviceVersionInfo_ = null;
      }
      return serviceVersionInfoBuilder_;
    }

    private int sessionKeyType_ = 1;
    /**
     * <pre>
     * Optional field that contains the algorithm type used to generate the
     * session_key and signature in a LICENSE message.
     * </pre>
     *
     * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
     * @return Whether the sessionKeyType field is set.
     */
    @java.lang.Override public boolean hasSessionKeyType() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <pre>
     * Optional field that contains the algorithm type used to generate the
     * session_key and signature in a LICENSE message.
     * </pre>
     *
     * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
     * @return The sessionKeyType.
     */
    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType getSessionKeyType() {
      de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType result = de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType.forNumber(sessionKeyType_);
      return result == null ? de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType.WRAPPED_AES_KEY : result;
    }
    /**
     * <pre>
     * Optional field that contains the algorithm type used to generate the
     * session_key and signature in a LICENSE message.
     * </pre>
     *
     * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
     * @param value The sessionKeyType to set.
     * @return This builder for chaining.
     */
    public Builder setSessionKeyType(de.klassenserver7b.widevine4j.protobuf.SignedMessage.SessionKeyType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000080;
      sessionKeyType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional field that contains the algorithm type used to generate the
     * session_key and signature in a LICENSE message.
     * </pre>
     *
     * <code>optional .SignedMessage.SessionKeyType session_key_type = 8 [default = WRAPPED_AES_KEY];</code>
     * @return This builder for chaining.
     */
    public Builder clearSessionKeyType() {
      bitField0_ = (bitField0_ & ~0x00000080);
      sessionKeyType_ = 1;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString oemcryptoCoreMessage_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * The core message is the simple serialization of fields used by OEMCrypto.
     * This field was introduced in OEMCrypto API v16.
     * </pre>
     *
     * <code>optional bytes oemcrypto_core_message = 9;</code>
     * @return Whether the oemcryptoCoreMessage field is set.
     */
    @java.lang.Override
    public boolean hasOemcryptoCoreMessage() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <pre>
     * The core message is the simple serialization of fields used by OEMCrypto.
     * This field was introduced in OEMCrypto API v16.
     * </pre>
     *
     * <code>optional bytes oemcrypto_core_message = 9;</code>
     * @return The oemcryptoCoreMessage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getOemcryptoCoreMessage() {
      return oemcryptoCoreMessage_;
    }
    /**
     * <pre>
     * The core message is the simple serialization of fields used by OEMCrypto.
     * This field was introduced in OEMCrypto API v16.
     * </pre>
     *
     * <code>optional bytes oemcrypto_core_message = 9;</code>
     * @param value The oemcryptoCoreMessage to set.
     * @return This builder for chaining.
     */
    public Builder setOemcryptoCoreMessage(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      oemcryptoCoreMessage_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The core message is the simple serialization of fields used by OEMCrypto.
     * This field was introduced in OEMCrypto API v16.
     * </pre>
     *
     * <code>optional bytes oemcrypto_core_message = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearOemcryptoCoreMessage() {
      bitField0_ = (bitField0_ & ~0x00000100);
      oemcryptoCoreMessage_ = getDefaultInstance().getOemcryptoCoreMessage();
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SignedMessage)
  }

  // @@protoc_insertion_point(class_scope:SignedMessage)
  private static final de.klassenserver7b.widevine4j.protobuf.SignedMessage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.SignedMessage();
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedMessage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SignedMessage>
      PARSER = new com.google.protobuf.AbstractParser<SignedMessage>() {
    @java.lang.Override
    public SignedMessage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SignedMessage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignedMessage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.SignedMessage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

