// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

/**
 * <pre>
 * DrmCertificate signed by a higher (CA) DRM certificate.
 * </pre>
 *
 * Protobuf type {@code SignedDrmCertificate}
 */
public final class SignedDrmCertificate extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:SignedDrmCertificate)
    SignedDrmCertificateOrBuilder {
private static final long serialVersionUID = 0L;
  // Use SignedDrmCertificate.newBuilder() to construct.
  private SignedDrmCertificate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SignedDrmCertificate() {
    drmCertificate_ = com.google.protobuf.ByteString.EMPTY;
    signature_ = com.google.protobuf.ByteString.EMPTY;
    hashAlgorithm_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new SignedDrmCertificate();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedDrmCertificate_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedDrmCertificate_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.class, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.Builder.class);
  }

  private int bitField0_;
  public static final int DRM_CERTIFICATE_FIELD_NUMBER = 1;
  private com.google.protobuf.ByteString drmCertificate_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Serialized certificate. Required.
   * </pre>
   *
   * <code>optional bytes drm_certificate = 1;</code>
   * @return Whether the drmCertificate field is set.
   */
  @java.lang.Override
  public boolean hasDrmCertificate() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * Serialized certificate. Required.
   * </pre>
   *
   * <code>optional bytes drm_certificate = 1;</code>
   * @return The drmCertificate.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getDrmCertificate() {
    return drmCertificate_;
  }

  public static final int SIGNATURE_FIELD_NUMBER = 2;
  private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
  /**
   * <pre>
   * Signature of certificate. Signed with root or intermediate
   * certificate specified below. Required.
   * </pre>
   *
   * <code>optional bytes signature = 2;</code>
   * @return Whether the signature field is set.
   */
  @java.lang.Override
  public boolean hasSignature() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Signature of certificate. Signed with root or intermediate
   * certificate specified below. Required.
   * </pre>
   *
   * <code>optional bytes signature = 2;</code>
   * @return The signature.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getSignature() {
    return signature_;
  }

  public static final int SIGNER_FIELD_NUMBER = 3;
  private de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate signer_;
  /**
   * <pre>
   * SignedDrmCertificate used to sign this certificate.
   * </pre>
   *
   * <code>optional .SignedDrmCertificate signer = 3;</code>
   * @return Whether the signer field is set.
   */
  @java.lang.Override
  public boolean hasSigner() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <pre>
   * SignedDrmCertificate used to sign this certificate.
   * </pre>
   *
   * <code>optional .SignedDrmCertificate signer = 3;</code>
   * @return The signer.
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate getSigner() {
    return signer_ == null ? de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.getDefaultInstance() : signer_;
  }
  /**
   * <pre>
   * SignedDrmCertificate used to sign this certificate.
   * </pre>
   *
   * <code>optional .SignedDrmCertificate signer = 3;</code>
   */
  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificateOrBuilder getSignerOrBuilder() {
    return signer_ == null ? de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.getDefaultInstance() : signer_;
  }

  public static final int HASH_ALGORITHM_FIELD_NUMBER = 4;
  private int hashAlgorithm_ = 0;
  /**
   * <pre>
   * Optional field that indicates the hash algorithm used in signature scheme.
   * </pre>
   *
   * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
   * @return Whether the hashAlgorithm field is set.
   */
  @java.lang.Override public boolean hasHashAlgorithm() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <pre>
   * Optional field that indicates the hash algorithm used in signature scheme.
   * </pre>
   *
   * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
   * @return The hashAlgorithm.
   */
  @java.lang.Override public de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto getHashAlgorithm() {
    de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto result = de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto.forNumber(hashAlgorithm_);
    return result == null ? de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto.HASH_ALGORITHM_UNSPECIFIED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBytes(1, drmCertificate_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeBytes(2, signature_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      output.writeMessage(3, getSigner());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, hashAlgorithm_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(1, drmCertificate_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(2, signature_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getSigner());
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, hashAlgorithm_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate)) {
      return super.equals(obj);
    }
    de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate other = (de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate) obj;

    if (hasDrmCertificate() != other.hasDrmCertificate()) return false;
    if (hasDrmCertificate()) {
      if (!getDrmCertificate()
          .equals(other.getDrmCertificate())) return false;
    }
    if (hasSignature() != other.hasSignature()) return false;
    if (hasSignature()) {
      if (!getSignature()
          .equals(other.getSignature())) return false;
    }
    if (hasSigner() != other.hasSigner()) return false;
    if (hasSigner()) {
      if (!getSigner()
          .equals(other.getSigner())) return false;
    }
    if (hasHashAlgorithm() != other.hasHashAlgorithm()) return false;
    if (hasHashAlgorithm()) {
      if (hashAlgorithm_ != other.hashAlgorithm_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDrmCertificate()) {
      hash = (37 * hash) + DRM_CERTIFICATE_FIELD_NUMBER;
      hash = (53 * hash) + getDrmCertificate().hashCode();
    }
    if (hasSignature()) {
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
    }
    if (hasSigner()) {
      hash = (37 * hash) + SIGNER_FIELD_NUMBER;
      hash = (53 * hash) + getSigner().hashCode();
    }
    if (hasHashAlgorithm()) {
      hash = (37 * hash) + HASH_ALGORITHM_FIELD_NUMBER;
      hash = (53 * hash) + hashAlgorithm_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DrmCertificate signed by a higher (CA) DRM certificate.
   * </pre>
   *
   * Protobuf type {@code SignedDrmCertificate}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:SignedDrmCertificate)
      de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificateOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedDrmCertificate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedDrmCertificate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.class, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.Builder.class);
    }

    // Construct using de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSignerFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      drmCertificate_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      signer_ = null;
      if (signerBuilder_ != null) {
        signerBuilder_.dispose();
        signerBuilder_ = null;
      }
      hashAlgorithm_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return de.klassenserver7b.widevine4j.protobuf.WvProto2.internal_static_SignedDrmCertificate_descriptor;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate getDefaultInstanceForType() {
      return de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.getDefaultInstance();
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate build() {
      de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate buildPartial() {
      de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate result = new de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.drmCertificate_ = drmCertificate_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.signature_ = signature_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.signer_ = signerBuilder_ == null
            ? signer_
            : signerBuilder_.build();
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.hashAlgorithm_ = hashAlgorithm_;
        to_bitField0_ |= 0x00000008;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate) {
        return mergeFrom((de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate other) {
      if (other == de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.getDefaultInstance()) return this;
      if (other.hasDrmCertificate()) {
        setDrmCertificate(other.getDrmCertificate());
      }
      if (other.hasSignature()) {
        setSignature(other.getSignature());
      }
      if (other.hasSigner()) {
        mergeSigner(other.getSigner());
      }
      if (other.hasHashAlgorithm()) {
        setHashAlgorithm(other.getHashAlgorithm());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              drmCertificate_ = input.readBytes();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              signature_ = input.readBytes();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              input.readMessage(
                  getSignerFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              int tmpRaw = input.readEnum();
              de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto tmpValue =
                  de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto.forNumber(tmpRaw);
              if (tmpValue == null) {
                mergeUnknownVarintField(4, tmpRaw);
              } else {
                hashAlgorithm_ = tmpRaw;
                bitField0_ |= 0x00000008;
              }
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.ByteString drmCertificate_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Serialized certificate. Required.
     * </pre>
     *
     * <code>optional bytes drm_certificate = 1;</code>
     * @return Whether the drmCertificate field is set.
     */
    @java.lang.Override
    public boolean hasDrmCertificate() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * Serialized certificate. Required.
     * </pre>
     *
     * <code>optional bytes drm_certificate = 1;</code>
     * @return The drmCertificate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getDrmCertificate() {
      return drmCertificate_;
    }
    /**
     * <pre>
     * Serialized certificate. Required.
     * </pre>
     *
     * <code>optional bytes drm_certificate = 1;</code>
     * @param value The drmCertificate to set.
     * @return This builder for chaining.
     */
    public Builder setDrmCertificate(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      drmCertificate_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Serialized certificate. Required.
     * </pre>
     *
     * <code>optional bytes drm_certificate = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDrmCertificate() {
      bitField0_ = (bitField0_ & ~0x00000001);
      drmCertificate_ = getDefaultInstance().getDrmCertificate();
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <pre>
     * Signature of certificate. Signed with root or intermediate
     * certificate specified below. Required.
     * </pre>
     *
     * <code>optional bytes signature = 2;</code>
     * @return Whether the signature field is set.
     */
    @java.lang.Override
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Signature of certificate. Signed with root or intermediate
     * certificate specified below. Required.
     * </pre>
     *
     * <code>optional bytes signature = 2;</code>
     * @return The signature.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <pre>
     * Signature of certificate. Signed with root or intermediate
     * certificate specified below. Required.
     * </pre>
     *
     * <code>optional bytes signature = 2;</code>
     * @param value The signature to set.
     * @return This builder for chaining.
     */
    public Builder setSignature(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      signature_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Signature of certificate. Signed with root or intermediate
     * certificate specified below. Required.
     * </pre>
     *
     * <code>optional bytes signature = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      signature_ = getDefaultInstance().getSignature();
      onChanged();
      return this;
    }

    private de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate signer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.Builder, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificateOrBuilder> signerBuilder_;
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     * @return Whether the signer field is set.
     */
    public boolean hasSigner() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     * @return The signer.
     */
    public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate getSigner() {
      if (signerBuilder_ == null) {
        return signer_ == null ? de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.getDefaultInstance() : signer_;
      } else {
        return signerBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     */
    public Builder setSigner(de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate value) {
      if (signerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        signer_ = value;
      } else {
        signerBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     */
    public Builder setSigner(
        de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.Builder builderForValue) {
      if (signerBuilder_ == null) {
        signer_ = builderForValue.build();
      } else {
        signerBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     */
    public Builder mergeSigner(de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate value) {
      if (signerBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0) &&
          signer_ != null &&
          signer_ != de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.getDefaultInstance()) {
          getSignerBuilder().mergeFrom(value);
        } else {
          signer_ = value;
        }
      } else {
        signerBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     */
    public Builder clearSigner() {
      bitField0_ = (bitField0_ & ~0x00000004);
      signer_ = null;
      if (signerBuilder_ != null) {
        signerBuilder_.dispose();
        signerBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.Builder getSignerBuilder() {
      bitField0_ |= 0x00000004;
      onChanged();
      return getSignerFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     */
    public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificateOrBuilder getSignerOrBuilder() {
      if (signerBuilder_ != null) {
        return signerBuilder_.getMessageOrBuilder();
      } else {
        return signer_ == null ?
            de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.getDefaultInstance() : signer_;
      }
    }
    /**
     * <pre>
     * SignedDrmCertificate used to sign this certificate.
     * </pre>
     *
     * <code>optional .SignedDrmCertificate signer = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.Builder, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificateOrBuilder> 
        getSignerFieldBuilder() {
      if (signerBuilder_ == null) {
        signerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate.Builder, de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificateOrBuilder>(
                getSigner(),
                getParentForChildren(),
                isClean());
        signer_ = null;
      }
      return signerBuilder_;
    }

    private int hashAlgorithm_ = 0;
    /**
     * <pre>
     * Optional field that indicates the hash algorithm used in signature scheme.
     * </pre>
     *
     * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
     * @return Whether the hashAlgorithm field is set.
     */
    @java.lang.Override public boolean hasHashAlgorithm() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Optional field that indicates the hash algorithm used in signature scheme.
     * </pre>
     *
     * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
     * @return The hashAlgorithm.
     */
    @java.lang.Override
    public de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto getHashAlgorithm() {
      de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto result = de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto.forNumber(hashAlgorithm_);
      return result == null ? de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto.HASH_ALGORITHM_UNSPECIFIED : result;
    }
    /**
     * <pre>
     * Optional field that indicates the hash algorithm used in signature scheme.
     * </pre>
     *
     * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
     * @param value The hashAlgorithm to set.
     * @return This builder for chaining.
     */
    public Builder setHashAlgorithm(de.klassenserver7b.widevine4j.protobuf.HashAlgorithmProto value) {
      if (value == null) {
        throw new NullPointerException();
      }
      bitField0_ |= 0x00000008;
      hashAlgorithm_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Optional field that indicates the hash algorithm used in signature scheme.
     * </pre>
     *
     * <code>optional .HashAlgorithmProto hash_algorithm = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearHashAlgorithm() {
      bitField0_ = (bitField0_ & ~0x00000008);
      hashAlgorithm_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:SignedDrmCertificate)
  }

  // @@protoc_insertion_point(class_scope:SignedDrmCertificate)
  private static final de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate();
  }

  public static de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<SignedDrmCertificate>
      PARSER = new com.google.protobuf.AbstractParser<SignedDrmCertificate>() {
    @java.lang.Override
    public SignedDrmCertificate parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SignedDrmCertificate> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SignedDrmCertificate> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public de.klassenserver7b.widevine4j.protobuf.SignedDrmCertificate getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

