// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface VersionInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:VersionInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * License SDK version reported by the Widevine License SDK. This field
   * is populated automatically by the SDK.
   * </pre>
   *
   * <code>optional string license_sdk_version = 1;</code>
   * @return Whether the licenseSdkVersion field is set.
   */
  boolean hasLicenseSdkVersion();
  /**
   * <pre>
   * License SDK version reported by the Widevine License SDK. This field
   * is populated automatically by the SDK.
   * </pre>
   *
   * <code>optional string license_sdk_version = 1;</code>
   * @return The licenseSdkVersion.
   */
  java.lang.String getLicenseSdkVersion();
  /**
   * <pre>
   * License SDK version reported by the Widevine License SDK. This field
   * is populated automatically by the SDK.
   * </pre>
   *
   * <code>optional string license_sdk_version = 1;</code>
   * @return The bytes for licenseSdkVersion.
   */
  com.google.protobuf.ByteString
      getLicenseSdkVersionBytes();

  /**
   * <pre>
   * Version of the service hosting the license SDK. This field is optional.
   * It may be provided by the hosting service.
   * </pre>
   *
   * <code>optional string license_service_version = 2;</code>
   * @return Whether the licenseServiceVersion field is set.
   */
  boolean hasLicenseServiceVersion();
  /**
   * <pre>
   * Version of the service hosting the license SDK. This field is optional.
   * It may be provided by the hosting service.
   * </pre>
   *
   * <code>optional string license_service_version = 2;</code>
   * @return The licenseServiceVersion.
   */
  java.lang.String getLicenseServiceVersion();
  /**
   * <pre>
   * Version of the service hosting the license SDK. This field is optional.
   * It may be provided by the hosting service.
   * </pre>
   *
   * <code>optional string license_service_version = 2;</code>
   * @return The bytes for licenseServiceVersion.
   */
  com.google.protobuf.ByteString
      getLicenseServiceVersionBytes();
}
