// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wv_proto2.proto

package de.klassenserver7b.widevine4j.protobuf;

public interface WidevinePsshDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:WidevinePsshData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Entitlement or content key IDs. Can onnly present in SINGLE or ENTITLEMENT
   * PSSHs. May be repeated to facilitate delivery of multiple keys in a
   * single license. Cannot be used in conjunction with content_id or
   * group_ids, which are the preferred mechanism.
   * </pre>
   *
   * <code>repeated bytes key_ids = 2;</code>
   * @return A list containing the keyIds.
   */
  java.util.List<com.google.protobuf.ByteString> getKeyIdsList();
  /**
   * <pre>
   * Entitlement or content key IDs. Can onnly present in SINGLE or ENTITLEMENT
   * PSSHs. May be repeated to facilitate delivery of multiple keys in a
   * single license. Cannot be used in conjunction with content_id or
   * group_ids, which are the preferred mechanism.
   * </pre>
   *
   * <code>repeated bytes key_ids = 2;</code>
   * @return The count of keyIds.
   */
  int getKeyIdsCount();
  /**
   * <pre>
   * Entitlement or content key IDs. Can onnly present in SINGLE or ENTITLEMENT
   * PSSHs. May be repeated to facilitate delivery of multiple keys in a
   * single license. Cannot be used in conjunction with content_id or
   * group_ids, which are the preferred mechanism.
   * </pre>
   *
   * <code>repeated bytes key_ids = 2;</code>
   * @param index The index of the element to return.
   * @return The keyIds at the given index.
   */
  com.google.protobuf.ByteString getKeyIds(int index);

  /**
   * <pre>
   * Content identifier which may map to multiple entitlement or content key
   * IDs to facilitate the delivery of multiple keys in a single license.
   * Cannot be present in conjunction with key_ids, but if used must be in all
   * PSSHs.
   * </pre>
   *
   * <code>optional bytes content_id = 4;</code>
   * @return Whether the contentId field is set.
   */
  boolean hasContentId();
  /**
   * <pre>
   * Content identifier which may map to multiple entitlement or content key
   * IDs to facilitate the delivery of multiple keys in a single license.
   * Cannot be present in conjunction with key_ids, but if used must be in all
   * PSSHs.
   * </pre>
   *
   * <code>optional bytes content_id = 4;</code>
   * @return The contentId.
   */
  com.google.protobuf.ByteString getContentId();

  /**
   * <pre>
   * Crypto period index, for media using key rotation. Always corresponds to
   * The content key period. This means that if using entitlement licensing
   * the ENTITLED_KEY PSSHs will have sequential crypto_period_index's, whereas
   * the ENTITELEMENT PSSHs will have gaps in the sequence. Required if doing
   * key rotation.
   * </pre>
   *
   * <code>optional uint32 crypto_period_index = 7;</code>
   * @return Whether the cryptoPeriodIndex field is set.
   */
  boolean hasCryptoPeriodIndex();
  /**
   * <pre>
   * Crypto period index, for media using key rotation. Always corresponds to
   * The content key period. This means that if using entitlement licensing
   * the ENTITLED_KEY PSSHs will have sequential crypto_period_index's, whereas
   * the ENTITELEMENT PSSHs will have gaps in the sequence. Required if doing
   * key rotation.
   * </pre>
   *
   * <code>optional uint32 crypto_period_index = 7;</code>
   * @return The cryptoPeriodIndex.
   */
  int getCryptoPeriodIndex();

  /**
   * <pre>
   * Protection scheme identifying the encryption algorithm. The protection
   * scheme is represented as a uint32 value. The uint32 contains 4 bytes each
   * representing a single ascii character in one of the 4CC protection scheme
   * values. To be deprecated in favor of signaling from content.
   * 'cenc' (AES-CTR) protection_scheme = 0x63656E63,
   * 'cbc1' (AES-CBC) protection_scheme = 0x63626331,
   * 'cens' (AES-CTR pattern encryption) protection_scheme = 0x63656E73,
   * 'cbcs' (AES-CBC pattern encryption) protection_scheme = 0x63626373.
   * </pre>
   *
   * <code>optional uint32 protection_scheme = 9;</code>
   * @return Whether the protectionScheme field is set.
   */
  boolean hasProtectionScheme();
  /**
   * <pre>
   * Protection scheme identifying the encryption algorithm. The protection
   * scheme is represented as a uint32 value. The uint32 contains 4 bytes each
   * representing a single ascii character in one of the 4CC protection scheme
   * values. To be deprecated in favor of signaling from content.
   * 'cenc' (AES-CTR) protection_scheme = 0x63656E63,
   * 'cbc1' (AES-CBC) protection_scheme = 0x63626331,
   * 'cens' (AES-CTR pattern encryption) protection_scheme = 0x63656E73,
   * 'cbcs' (AES-CBC pattern encryption) protection_scheme = 0x63626373.
   * </pre>
   *
   * <code>optional uint32 protection_scheme = 9;</code>
   * @return The protectionScheme.
   */
  int getProtectionScheme();

  /**
   * <pre>
   * Optional. For media using key rotation, this represents the duration
   * of each crypto period in seconds.
   * </pre>
   *
   * <code>optional uint32 crypto_period_seconds = 10;</code>
   * @return Whether the cryptoPeriodSeconds field is set.
   */
  boolean hasCryptoPeriodSeconds();
  /**
   * <pre>
   * Optional. For media using key rotation, this represents the duration
   * of each crypto period in seconds.
   * </pre>
   *
   * <code>optional uint32 crypto_period_seconds = 10;</code>
   * @return The cryptoPeriodSeconds.
   */
  int getCryptoPeriodSeconds();

  /**
   * <pre>
   * Type of PSSH. Required if not SINGLE.
   * </pre>
   *
   * <code>optional .WidevinePsshData.Type type = 11 [default = SINGLE];</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   * Type of PSSH. Required if not SINGLE.
   * </pre>
   *
   * <code>optional .WidevinePsshData.Type type = 11 [default = SINGLE];</code>
   * @return The type.
   */
  de.klassenserver7b.widevine4j.protobuf.WidevinePsshData.Type getType();

  /**
   * <pre>
   * Key sequence for Widevine-managed keys. Optional.
   * </pre>
   *
   * <code>optional uint32 key_sequence = 12;</code>
   * @return Whether the keySequence field is set.
   */
  boolean hasKeySequence();
  /**
   * <pre>
   * Key sequence for Widevine-managed keys. Optional.
   * </pre>
   *
   * <code>optional uint32 key_sequence = 12;</code>
   * @return The keySequence.
   */
  int getKeySequence();

  /**
   * <pre>
   * Group identifiers for all groups to which the content belongs. This can
   * be used to deliver licenses to unlock multiple titles / channels.
   * Optional, and may only be present in ENTITLEMENT and ENTITLED_KEY PSSHs, and
   * not in conjunction with key_ids.
   * </pre>
   *
   * <code>repeated bytes group_ids = 13;</code>
   * @return A list containing the groupIds.
   */
  java.util.List<com.google.protobuf.ByteString> getGroupIdsList();
  /**
   * <pre>
   * Group identifiers for all groups to which the content belongs. This can
   * be used to deliver licenses to unlock multiple titles / channels.
   * Optional, and may only be present in ENTITLEMENT and ENTITLED_KEY PSSHs, and
   * not in conjunction with key_ids.
   * </pre>
   *
   * <code>repeated bytes group_ids = 13;</code>
   * @return The count of groupIds.
   */
  int getGroupIdsCount();
  /**
   * <pre>
   * Group identifiers for all groups to which the content belongs. This can
   * be used to deliver licenses to unlock multiple titles / channels.
   * Optional, and may only be present in ENTITLEMENT and ENTITLED_KEY PSSHs, and
   * not in conjunction with key_ids.
   * </pre>
   *
   * <code>repeated bytes group_ids = 13;</code>
   * @param index The index of the element to return.
   * @return The groupIds at the given index.
   */
  com.google.protobuf.ByteString getGroupIds(int index);

  /**
   * <pre>
   * Copy/copies of the content key used to decrypt the media stream in which
   * the PSSH box is embedded, each wrapped with a different entitlement key.
   * May also contain sub-licenses to support devices with OEMCrypto 13 or
   * older. May be repeated if using group entitlement keys. Present only in
   * PSSHs of type ENTITLED_KEY.
   * </pre>
   *
   * <code>repeated .WidevinePsshData.EntitledKey entitled_keys = 14;</code>
   */
  java.util.List<de.klassenserver7b.widevine4j.protobuf.WidevinePsshData.EntitledKey> 
      getEntitledKeysList();
  /**
   * <pre>
   * Copy/copies of the content key used to decrypt the media stream in which
   * the PSSH box is embedded, each wrapped with a different entitlement key.
   * May also contain sub-licenses to support devices with OEMCrypto 13 or
   * older. May be repeated if using group entitlement keys. Present only in
   * PSSHs of type ENTITLED_KEY.
   * </pre>
   *
   * <code>repeated .WidevinePsshData.EntitledKey entitled_keys = 14;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.WidevinePsshData.EntitledKey getEntitledKeys(int index);
  /**
   * <pre>
   * Copy/copies of the content key used to decrypt the media stream in which
   * the PSSH box is embedded, each wrapped with a different entitlement key.
   * May also contain sub-licenses to support devices with OEMCrypto 13 or
   * older. May be repeated if using group entitlement keys. Present only in
   * PSSHs of type ENTITLED_KEY.
   * </pre>
   *
   * <code>repeated .WidevinePsshData.EntitledKey entitled_keys = 14;</code>
   */
  int getEntitledKeysCount();
  /**
   * <pre>
   * Copy/copies of the content key used to decrypt the media stream in which
   * the PSSH box is embedded, each wrapped with a different entitlement key.
   * May also contain sub-licenses to support devices with OEMCrypto 13 or
   * older. May be repeated if using group entitlement keys. Present only in
   * PSSHs of type ENTITLED_KEY.
   * </pre>
   *
   * <code>repeated .WidevinePsshData.EntitledKey entitled_keys = 14;</code>
   */
  java.util.List<? extends de.klassenserver7b.widevine4j.protobuf.WidevinePsshData.EntitledKeyOrBuilder> 
      getEntitledKeysOrBuilderList();
  /**
   * <pre>
   * Copy/copies of the content key used to decrypt the media stream in which
   * the PSSH box is embedded, each wrapped with a different entitlement key.
   * May also contain sub-licenses to support devices with OEMCrypto 13 or
   * older. May be repeated if using group entitlement keys. Present only in
   * PSSHs of type ENTITLED_KEY.
   * </pre>
   *
   * <code>repeated .WidevinePsshData.EntitledKey entitled_keys = 14;</code>
   */
  de.klassenserver7b.widevine4j.protobuf.WidevinePsshData.EntitledKeyOrBuilder getEntitledKeysOrBuilder(
      int index);

  /**
   * <pre>
   * Video feature identifier, which is used in conjunction with |content_id|
   * to determine the set of keys to be returned in the license. Cannot be
   * present in conjunction with |key_ids|.
   * Current values are "HDR".
   * </pre>
   *
   * <code>optional string video_feature = 15;</code>
   * @return Whether the videoFeature field is set.
   */
  boolean hasVideoFeature();
  /**
   * <pre>
   * Video feature identifier, which is used in conjunction with |content_id|
   * to determine the set of keys to be returned in the license. Cannot be
   * present in conjunction with |key_ids|.
   * Current values are "HDR".
   * </pre>
   *
   * <code>optional string video_feature = 15;</code>
   * @return The videoFeature.
   */
  java.lang.String getVideoFeature();
  /**
   * <pre>
   * Video feature identifier, which is used in conjunction with |content_id|
   * to determine the set of keys to be returned in the license. Cannot be
   * present in conjunction with |key_ids|.
   * Current values are "HDR".
   * </pre>
   *
   * <code>optional string video_feature = 15;</code>
   * @return The bytes for videoFeature.
   */
  com.google.protobuf.ByteString
      getVideoFeatureBytes();

  /**
   * <code>optional .WidevinePsshData.Algorithm algorithm = 1 [deprecated = true];</code>
   * @deprecated WidevinePsshData.algorithm is deprecated.
   *     See wv_proto2.proto;l=720
   * @return Whether the algorithm field is set.
   */
  @java.lang.Deprecated boolean hasAlgorithm();
  /**
   * <code>optional .WidevinePsshData.Algorithm algorithm = 1 [deprecated = true];</code>
   * @deprecated WidevinePsshData.algorithm is deprecated.
   *     See wv_proto2.proto;l=720
   * @return The algorithm.
   */
  @java.lang.Deprecated de.klassenserver7b.widevine4j.protobuf.WidevinePsshData.Algorithm getAlgorithm();

  /**
   * <pre>
   * Content provider name.
   * </pre>
   *
   * <code>optional string provider = 3 [deprecated = true];</code>
   * @deprecated WidevinePsshData.provider is deprecated.
   *     See wv_proto2.proto;l=723
   * @return Whether the provider field is set.
   */
  @java.lang.Deprecated boolean hasProvider();
  /**
   * <pre>
   * Content provider name.
   * </pre>
   *
   * <code>optional string provider = 3 [deprecated = true];</code>
   * @deprecated WidevinePsshData.provider is deprecated.
   *     See wv_proto2.proto;l=723
   * @return The provider.
   */
  @java.lang.Deprecated java.lang.String getProvider();
  /**
   * <pre>
   * Content provider name.
   * </pre>
   *
   * <code>optional string provider = 3 [deprecated = true];</code>
   * @deprecated WidevinePsshData.provider is deprecated.
   *     See wv_proto2.proto;l=723
   * @return The bytes for provider.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getProviderBytes();

  /**
   * <pre>
   * Track type. Acceptable values are SD, HD and AUDIO. Used to
   * differentiate content keys used by an asset.
   * </pre>
   *
   * <code>optional string track_type = 5 [deprecated = true];</code>
   * @deprecated WidevinePsshData.track_type is deprecated.
   *     See wv_proto2.proto;l=727
   * @return Whether the trackType field is set.
   */
  @java.lang.Deprecated boolean hasTrackType();
  /**
   * <pre>
   * Track type. Acceptable values are SD, HD and AUDIO. Used to
   * differentiate content keys used by an asset.
   * </pre>
   *
   * <code>optional string track_type = 5 [deprecated = true];</code>
   * @deprecated WidevinePsshData.track_type is deprecated.
   *     See wv_proto2.proto;l=727
   * @return The trackType.
   */
  @java.lang.Deprecated java.lang.String getTrackType();
  /**
   * <pre>
   * Track type. Acceptable values are SD, HD and AUDIO. Used to
   * differentiate content keys used by an asset.
   * </pre>
   *
   * <code>optional string track_type = 5 [deprecated = true];</code>
   * @deprecated WidevinePsshData.track_type is deprecated.
   *     See wv_proto2.proto;l=727
   * @return The bytes for trackType.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getTrackTypeBytes();

  /**
   * <pre>
   * The name of a registered policy to be used for this asset.
   * </pre>
   *
   * <code>optional string policy = 6 [deprecated = true];</code>
   * @deprecated WidevinePsshData.policy is deprecated.
   *     See wv_proto2.proto;l=730
   * @return Whether the policy field is set.
   */
  @java.lang.Deprecated boolean hasPolicy();
  /**
   * <pre>
   * The name of a registered policy to be used for this asset.
   * </pre>
   *
   * <code>optional string policy = 6 [deprecated = true];</code>
   * @deprecated WidevinePsshData.policy is deprecated.
   *     See wv_proto2.proto;l=730
   * @return The policy.
   */
  @java.lang.Deprecated java.lang.String getPolicy();
  /**
   * <pre>
   * The name of a registered policy to be used for this asset.
   * </pre>
   *
   * <code>optional string policy = 6 [deprecated = true];</code>
   * @deprecated WidevinePsshData.policy is deprecated.
   *     See wv_proto2.proto;l=730
   * @return The bytes for policy.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getPolicyBytes();

  /**
   * <pre>
   * Optional protected context for group content. The grouped_license is a
   * serialized SignedMessage.
   * </pre>
   *
   * <code>optional bytes grouped_license = 8 [deprecated = true];</code>
   * @deprecated WidevinePsshData.grouped_license is deprecated.
   *     See wv_proto2.proto;l=734
   * @return Whether the groupedLicense field is set.
   */
  @java.lang.Deprecated boolean hasGroupedLicense();
  /**
   * <pre>
   * Optional protected context for group content. The grouped_license is a
   * serialized SignedMessage.
   * </pre>
   *
   * <code>optional bytes grouped_license = 8 [deprecated = true];</code>
   * @deprecated WidevinePsshData.grouped_license is deprecated.
   *     See wv_proto2.proto;l=734
   * @return The groupedLicense.
   */
  @java.lang.Deprecated com.google.protobuf.ByteString getGroupedLicense();
}
